// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AnswerQuestionApiQuestionsQuestionIdAnswerPostData, AnswerQuestionApiQuestionsQuestionIdAnswerPostErrors, AnswerQuestionApiQuestionsQuestionIdAnswerPostResponses, AskQuestionApiQuestionsPostData, AskQuestionApiQuestionsPostErrors, AskQuestionApiQuestionsPostResponses, ClaimRouteApiRoutesPostData, ClaimRouteApiRoutesPostErrors, ClaimRouteApiRoutesPostResponses, GetChunkApiChunksChunkIdGetData, GetChunkApiChunksChunkIdGetErrors, GetChunkApiChunksChunkIdGetResponses, GetEnvelopeApiChunksChunkIdEnvelopeGetData, GetEnvelopeApiChunksChunkIdEnvelopeGetErrors, GetEnvelopeApiChunksChunkIdEnvelopeGetResponses, GetPmItemApiChunksChunkIdPmItemGetData, GetPmItemApiChunksChunkIdPmItemGetErrors, GetPmItemApiChunksChunkIdPmItemGetResponses, GetQuestionApiQuestionsQuestionIdGetData, GetQuestionApiQuestionsQuestionIdGetErrors, GetQuestionApiQuestionsQuestionIdGetResponses, HealthApiHealthGetData, HealthApiHealthGetResponses, IngestChunkApiChunksPostData, IngestChunkApiChunksPostErrors, IngestChunkApiChunksPostResponses, IngestRunnerFactsApiEventsPostData, IngestRunnerFactsApiEventsPostErrors, IngestRunnerFactsApiEventsPostResponses, ListChunksApiChunksGetData, ListChunksApiChunksGetResponses, ListOpenQuestionsApiQuestionsGetData, ListOpenQuestionsApiQuestionsGetResponses, MintGraphApiGraphsPostData, MintGraphApiGraphsPostErrors, MintGraphApiGraphsPostResponses, PeekQueueApiQueuePeekGetData, PeekQueueApiQueuePeekGetResponses, ReadyApiReadyGetData, ReadyApiReadyGetResponses, ReportEscalationApiChunksChunkIdEscalationsPostData, ReportEscalationApiChunksChunkIdEscalationsPostErrors, ReportEscalationApiChunksChunkIdEscalationsPostResponses, ReportLeaseApiChunksChunkIdLeasesPostData, ReportLeaseApiChunksChunkIdLeasesPostErrors, ReportLeaseApiChunksChunkIdLeasesPostResponses, SubmitCompletionApiChunksChunkIdCompletionsPostData, SubmitCompletionApiChunksChunkIdCompletionsPostErrors, SubmitCompletionApiChunksChunkIdCompletionsPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List Chunks
 *
 * The fleet chunk list — derived status per chunk (D-004).
 */
export const listChunksApiChunksGet = <ThrowOnError extends boolean = false>(options?: Options<ListChunksApiChunksGetData, ThrowOnError>): RequestResult<ListChunksApiChunksGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListChunksApiChunksGetResponses, unknown, ThrowOnError>({ url: '/api/chunks', ...options });

/**
 * Ingest Chunk
 *
 * Ingest by pointer (D-047); 409 on a pointer held by a live chunk (D-093).
 */
export const ingestChunkApiChunksPost = <ThrowOnError extends boolean = false>(options: Options<IngestChunkApiChunksPostData, ThrowOnError>): RequestResult<IngestChunkApiChunksPostResponses, IngestChunkApiChunksPostErrors, ThrowOnError> => (options.client ?? client).post<IngestChunkApiChunksPostResponses, IngestChunkApiChunksPostErrors, ThrowOnError>({
    url: '/api/chunks',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Chunk
 *
 * One chunk aggregate in full — derived status, current node, route (D-036).
 */
export const getChunkApiChunksChunkIdGet = <ThrowOnError extends boolean = false>(options: Options<GetChunkApiChunksChunkIdGetData, ThrowOnError>): RequestResult<GetChunkApiChunksChunkIdGetResponses, GetChunkApiChunksChunkIdGetErrors, ThrowOnError> => (options.client ?? client).get<GetChunkApiChunksChunkIdGetResponses, GetChunkApiChunksChunkIdGetErrors, ThrowOnError>({ url: '/api/chunks/{chunk_id}', ...options });

/**
 * Submit Completion
 *
 * Apply a node-step's completion atomically; reply carries the next envelope (D-072).
 */
export const submitCompletionApiChunksChunkIdCompletionsPost = <ThrowOnError extends boolean = false>(options: Options<SubmitCompletionApiChunksChunkIdCompletionsPostData, ThrowOnError>): RequestResult<SubmitCompletionApiChunksChunkIdCompletionsPostResponses, SubmitCompletionApiChunksChunkIdCompletionsPostErrors, ThrowOnError> => (options.client ?? client).post<SubmitCompletionApiChunksChunkIdCompletionsPostResponses, SubmitCompletionApiChunksChunkIdCompletionsPostErrors, ThrowOnError>({
    url: '/api/chunks/{chunk_id}/completions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Envelope
 *
 * The chunk's current node envelope, idempotent — the lost-apply re-read (D-090).
 */
export const getEnvelopeApiChunksChunkIdEnvelopeGet = <ThrowOnError extends boolean = false>(options: Options<GetEnvelopeApiChunksChunkIdEnvelopeGetData, ThrowOnError>): RequestResult<GetEnvelopeApiChunksChunkIdEnvelopeGetResponses, GetEnvelopeApiChunksChunkIdEnvelopeGetErrors, ThrowOnError> => (options.client ?? client).get<GetEnvelopeApiChunksChunkIdEnvelopeGetResponses, GetEnvelopeApiChunksChunkIdEnvelopeGetErrors, ThrowOnError>({ url: '/api/chunks/{chunk_id}/envelope', ...options });

/**
 * Report Escalation
 *
 * Land a runner's ``escalation.recorded`` — the chunk derives ``needs_human`` (D-009).
 */
export const reportEscalationApiChunksChunkIdEscalationsPost = <ThrowOnError extends boolean = false>(options: Options<ReportEscalationApiChunksChunkIdEscalationsPostData, ThrowOnError>): RequestResult<ReportEscalationApiChunksChunkIdEscalationsPostResponses, ReportEscalationApiChunksChunkIdEscalationsPostErrors, ThrowOnError> => (options.client ?? client).post<ReportEscalationApiChunksChunkIdEscalationsPostResponses, ReportEscalationApiChunksChunkIdEscalationsPostErrors, ThrowOnError>({
    url: '/api/chunks/{chunk_id}/escalations',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Report Lease
 *
 * Land a runner's ``lease.minted`` — keeps the epoch fence in lockstep (D-044).
 */
export const reportLeaseApiChunksChunkIdLeasesPost = <ThrowOnError extends boolean = false>(options: Options<ReportLeaseApiChunksChunkIdLeasesPostData, ThrowOnError>): RequestResult<ReportLeaseApiChunksChunkIdLeasesPostResponses, ReportLeaseApiChunksChunkIdLeasesPostErrors, ThrowOnError> => (options.client ?? client).post<ReportLeaseApiChunksChunkIdLeasesPostResponses, ReportLeaseApiChunksChunkIdLeasesPostErrors, ThrowOnError>({
    url: '/api/chunks/{chunk_id}/leases',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Pm Item
 *
 * Pass-through PM item read — body + comments, contents never stored (D-047).
 */
export const getPmItemApiChunksChunkIdPmItemGet = <ThrowOnError extends boolean = false>(options: Options<GetPmItemApiChunksChunkIdPmItemGetData, ThrowOnError>): RequestResult<GetPmItemApiChunksChunkIdPmItemGetResponses, GetPmItemApiChunksChunkIdPmItemGetErrors, ThrowOnError> => (options.client ?? client).get<GetPmItemApiChunksChunkIdPmItemGetResponses, GetPmItemApiChunksChunkIdPmItemGetErrors, ThrowOnError>({ url: '/api/chunks/{chunk_id}/pm-item', ...options });

/**
 * Ingest Runner Facts
 *
 * Land runner-minted facts, idempotent by per-runner seq high-water (D-069/D-044).
 *
 * The store-and-forward ingest: ``lease.minted`` (the fence input) and
 * ``escalation.recorded`` ride the runner's outbound buffer here. A pushed seq at or
 * below the runner's high-water mark is already-applied and re-acked; a fresh one is
 * applied and advances the mark. Emits ``chunk-changed`` for each chunk a landed
 * fact touched so the board refreshes.
 */
export const ingestRunnerFactsApiEventsPost = <ThrowOnError extends boolean = false>(options: Options<IngestRunnerFactsApiEventsPostData, ThrowOnError>): RequestResult<IngestRunnerFactsApiEventsPostResponses, IngestRunnerFactsApiEventsPostErrors, ThrowOnError> => (options.client ?? client).post<IngestRunnerFactsApiEventsPostResponses, IngestRunnerFactsApiEventsPostErrors, ThrowOnError>({
    url: '/api/events',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Mint Graph
 *
 * Validate and mint an immutable graph; 422 on validation errors (D-071).
 */
export const mintGraphApiGraphsPost = <ThrowOnError extends boolean = false>(options: Options<MintGraphApiGraphsPostData, ThrowOnError>): RequestResult<MintGraphApiGraphsPostResponses, MintGraphApiGraphsPostErrors, ThrowOnError> => (options.client ?? client).post<MintGraphApiGraphsPostResponses, MintGraphApiGraphsPostErrors, ThrowOnError>({
    url: '/api/graphs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Health
 */
export const healthApiHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthApiHealthGetData, ThrowOnError>): RequestResult<HealthApiHealthGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthApiHealthGetResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

/**
 * List Open Questions
 *
 * Every open (unanswered) question across the fleet — the ``hub status`` surface.
 */
export const listOpenQuestionsApiQuestionsGet = <ThrowOnError extends boolean = false>(options?: Options<ListOpenQuestionsApiQuestionsGetData, ThrowOnError>): RequestResult<ListOpenQuestionsApiQuestionsGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListOpenQuestionsApiQuestionsGetResponses, unknown, ThrowOnError>({ url: '/api/questions', ...options });

/**
 * Ask Question
 *
 * Land a ``question.asked`` row — the chunk parks ``waiting_on_human`` ([ask-answer.md]).
 */
export const askQuestionApiQuestionsPost = <ThrowOnError extends boolean = false>(options: Options<AskQuestionApiQuestionsPostData, ThrowOnError>): RequestResult<AskQuestionApiQuestionsPostResponses, AskQuestionApiQuestionsPostErrors, ThrowOnError> => (options.client ?? client).post<AskQuestionApiQuestionsPostResponses, AskQuestionApiQuestionsPostErrors, ThrowOnError>({
    url: '/api/questions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Question
 *
 * One question with its derived answer state — the runner's answer poll (D-004).
 */
export const getQuestionApiQuestionsQuestionIdGet = <ThrowOnError extends boolean = false>(options: Options<GetQuestionApiQuestionsQuestionIdGetData, ThrowOnError>): RequestResult<GetQuestionApiQuestionsQuestionIdGetResponses, GetQuestionApiQuestionsQuestionIdGetErrors, ThrowOnError> => (options.client ?? client).get<GetQuestionApiQuestionsQuestionIdGetResponses, GetQuestionApiQuestionsQuestionIdGetErrors, ThrowOnError>({ url: '/api/questions/{question_id}', ...options });

/**
 * Answer Question
 *
 * Answer a question first-write-wins; 409 carries the winning answer ([ask-answer.md]).
 */
export const answerQuestionApiQuestionsQuestionIdAnswerPost = <ThrowOnError extends boolean = false>(options: Options<AnswerQuestionApiQuestionsQuestionIdAnswerPostData, ThrowOnError>): RequestResult<AnswerQuestionApiQuestionsQuestionIdAnswerPostResponses, AnswerQuestionApiQuestionsQuestionIdAnswerPostErrors, ThrowOnError> => (options.client ?? client).post<AnswerQuestionApiQuestionsQuestionIdAnswerPostResponses, AnswerQuestionApiQuestionsQuestionIdAnswerPostErrors, ThrowOnError>({
    url: '/api/questions/{question_id}/answer',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Peek Queue
 *
 * The hub-ordered ready queue, read-only (D-080).
 */
export const peekQueueApiQueuePeekGet = <ThrowOnError extends boolean = false>(options?: Options<PeekQueueApiQueuePeekGetData, ThrowOnError>): RequestResult<PeekQueueApiQueuePeekGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<PeekQueueApiQueuePeekGetResponses, unknown, ThrowOnError>({ url: '/api/queue/peek', ...options });

/**
 * Ready
 */
export const readyApiReadyGet = <ThrowOnError extends boolean = false>(options?: Options<ReadyApiReadyGetData, ThrowOnError>): RequestResult<ReadyApiReadyGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ReadyApiReadyGetResponses, unknown, ThrowOnError>({ url: '/api/ready', ...options });

/**
 * Claim Route
 *
 * Claim a chunk; 409 if already claimed, else the first node envelope (D-080).
 */
export const claimRouteApiRoutesPost = <ThrowOnError extends boolean = false>(options: Options<ClaimRouteApiRoutesPostData, ThrowOnError>): RequestResult<ClaimRouteApiRoutesPostResponses, ClaimRouteApiRoutesPostErrors, ThrowOnError> => (options.client ?? client).post<ClaimRouteApiRoutesPostResponses, ClaimRouteApiRoutesPostErrors, ThrowOnError>({
    url: '/api/routes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
