// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AnswerRequest
 *
 * The body of ``POST /questions/{id}/answer`` — the human's answer.
 */
export type AnswerRequest = {
    /**
     * Answer
     */
    answer: string;
    /**
     * Answered By
     */
    answered_by?: string;
};

/**
 * AnswerResult
 *
 * The answer write's outcome — first-write-wins CAS.
 *
 * ``won`` is True for the write that landed the row; the loser gets ``won=False`` with
 * the **winning** row so it can be told who already answered (the 409 body).
 */
export type AnswerResult = {
    /**
     * Answer
     */
    answer: string;
    /**
     * Answered At
     */
    answered_at: string;
    /**
     * Answered By
     */
    answered_by: string;
    /**
     * Question Id
     */
    question_id: string;
    /**
     * Won
     */
    won: boolean;
};

/**
 * ApplyOutcome
 *
 * What a completion's apply produced.
 */
export type ApplyOutcome = 'next' | 'hub_node_taken' | 'parked_at_gate' | 'migrated' | 'done' | 'failure';

/**
 * ApplyResponse
 *
 * The response to a completion submission.
 *
 * Exactly one of ``next_envelope`` (when ``outcome == next``) or ``detail`` (on a
 * non-advancing outcome) is meaningful; the ``outcome`` discriminates.
 */
export type ApplyResponse = {
    /**
     * Detail
     */
    detail?: string | null;
    next_envelope?: NodeEnvelope | null;
    outcome: ApplyOutcome;
};

/**
 * ArtifactKind
 *
 * The union discriminator.
 */
export type ArtifactKind = 'git_commit' | 'asset';

/**
 * ArtifactView
 *
 * One entry of a chunk's inline artifact store.
 *
 * ``key`` is the store key ``{node}.{artifact-name}.{epoch}`` — append-only, so
 * every re-run's entry is retained and latest-by-epoch resolution is the reader's.
 * ``content`` carries an **asset's** text verbatim (a review's findings
 * document); the ``repo``/``branch_name``/``commit_hash`` trio carries a
 * ``git_commit`` artifact's pinned reference (the hub stores the reference, never the
 * code).
 *
 * ``branch_url`` is the forge ``tree`` URL for the produced branch, resolved server-side
 * from the chunk's issue-shaped PM pointer so the board can link a ``git_commit``
 * to the branch on the forge; null when no forge web base is derivable — the row then
 * shows the branch name without a link (no broken link).
 *
 * ``recorded_at`` is the instant the artifact was attached, decoded from its id's
 * ULID timestamp (the store keeps no separate column); null for a malformed id.
 */
export type ArtifactView = {
    /**
     * Branch Name
     */
    branch_name?: string | null;
    /**
     * Branch Url
     */
    branch_url?: string | null;
    /**
     * Commit Hash
     */
    commit_hash?: string | null;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Epoch
     */
    epoch: number;
    /**
     * Key
     */
    key: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Name
     */
    name: string;
    /**
     * Node Id
     */
    node_id: string;
    /**
     * Node Name
     */
    node_name: string;
    /**
     * Recorded At
     */
    recorded_at?: string | null;
    /**
     * Repo
     */
    repo?: string | null;
};

/**
 * BounceView
 *
 * One recorded delivery kick-back (#64) — contention, not failure.
 *
 * Surfaced on chunk detail so the bounce history is readable — including once the
 * count crosses the node's ``bounce_cap`` and the chunk derives ``needs_human`` instead
 * of routing back — without itself being (or affecting) the chunk's derived status.
 * ``envelope`` is the raw JSON kick-back payload (cause detail, etc.) verbatim.
 */
export type BounceView = {
    /**
     * Cause
     */
    cause: string;
    /**
     * Envelope
     */
    envelope: string;
    /**
     * Recorded At
     */
    recorded_at: string;
};

/**
 * CheckResult
 *
 * One deterministic check's outcome, informing the verdict.
 */
export type CheckResult = {
    /**
     * Command
     */
    command: string;
    /**
     * Passed
     */
    passed: boolean;
};

/**
 * ChunkDetail
 *
 * The chunk aggregate in full — the board's chunk view and envelope feed.
 *
 * Carries the chunk's **transition history** and its inline **artifact store** so the
 * web app can render every node it visited, the review that failed once and looped
 * back to build, and the artifacts — the branch pointers merged and the review notes.
 */
export type ChunkDetail = {
    /**
     * Artifacts
     */
    artifacts?: Array<ArtifactView>;
    /**
     * Awaiting External Merge
     */
    awaiting_external_merge?: boolean;
    /**
     * Bounces
     */
    bounces?: Array<BounceView>;
    /**
     * Chunk Id
     */
    chunk_id: string;
    cost?: ChunkUsageTotalView;
    /**
     * Current Node Id
     */
    current_node_id: string | null;
    /**
     * Current Node Name
     */
    current_node_name?: string | null;
    decision?: DecisionView | null;
    escalation?: EscalationView | null;
    /**
     * Graph Id
     */
    graph_id: string;
    /**
     * History
     */
    history?: Array<TransitionView>;
    /**
     * Landed
     */
    landed?: boolean;
    /**
     * Latest Epoch
     */
    latest_epoch: number | null;
    /**
     * Migrations
     */
    migrations?: Array<MigrationView>;
    /**
     * Model
     */
    model: string;
    /**
     * Open Prs
     */
    open_prs?: Array<PrView>;
    pause?: PauseView | null;
    pending?: PendingView | null;
    /**
     * Pm Pointers
     */
    pm_pointers?: Array<PmPointerView>;
    /**
     * Questions
     */
    questions?: Array<QuestionView>;
    route?: RouteView | null;
    status: ChunkStatus;
    /**
     * Usage
     */
    usage?: Array<ChunkUsageView>;
};

/**
 * ChunkGraphUpdateRequest
 *
 * Repin a not-ready chunk's workflow graph (issue #27) — the target graph's id.
 */
export type ChunkGraphUpdateRequest = {
    /**
     * Graph Id
     */
    graph_id: string;
};

/**
 * ChunkGraphView
 *
 * A chunk's current graph selection — the read/write shape issue #27's board editor uses.
 */
export type ChunkGraphView = {
    /**
     * Chunk Id
     */
    chunk_id: string;
    /**
     * Graph Id
     */
    graph_id: string;
};

/**
 * ChunkGroupRequest
 *
 * Merge unacquired chunks into one — the board's Group control.
 *
 * ``merge_chunk_ids`` are the ready chunks folded into the path's survivor chunk; the
 * survivor absorbs the union of their PM pointers and the merged chunks are discarded as
 * ephemeral. Self-references and duplicates are ignored; a non-ready member is
 * rejected ``409``.
 */
export type ChunkGroupRequest = {
    /**
     * Merge Chunk Ids
     */
    merge_chunk_ids: Array<string>;
};

/**
 * ChunkGroupResponse
 *
 * The survivor chunk after a group — its id and the union of PM pointers it carries.
 */
export type ChunkGroupResponse = {
    /**
     * Chunk Id
     */
    chunk_id: string;
    /**
     * Merged Chunk Ids
     */
    merged_chunk_ids?: Array<string>;
    /**
     * Pm Pointers
     */
    pm_pointers?: Array<PmPointerModel>;
};

/**
 * ChunkIngestRequest
 *
 * Ingest by source-native token — specific items always, batch fine.
 *
 * Each token is resolved against the configured PM sources' own grammar
 * (``IPmSource.parse``): ``{name}:{ref}``, ``{name}#{ref}``, or the item's own URL.
 * Tokens only — no pre-resolved ``{source, ref}`` shape travels alongside them; a
 * second intake shape would reintroduce exactly the config-blind guess that
 * resolving against the configured sources removes.
 */
export type ChunkIngestRequest = {
    /**
     * Tokens
     */
    tokens: Array<string>;
};

/**
 * ChunkIngestResponse
 *
 * The minted chunk id.
 */
export type ChunkIngestResponse = {
    /**
     * Chunk Id
     */
    chunk_id: string;
};

/**
 * ChunkModelUpdateRequest
 *
 * Repin a not-ready chunk's model selection (issue #27).
 */
export type ChunkModelUpdateRequest = {
    /**
     * Model
     */
    model: string;
};

/**
 * ChunkModelView
 *
 * A chunk's current model selection — the read/write shape issue #27's board editor uses.
 */
export type ChunkModelView = {
    /**
     * Chunk Id
     */
    chunk_id: string;
    /**
     * Model
     */
    model: string;
};

/**
 * ChunkPauseRequest
 *
 * Set or clear a chunk's operator pause brake — records who flipped it (issue #46).
 */
export type ChunkPauseRequest = {
    /**
     * By
     */
    by?: string;
};

/**
 * ChunkStatus
 *
 * The derived chunk statuses. Never stored — always a query result.
 */
export type ChunkStatus = 'not_ready' | 'ready' | 'running' | 'delivering' | 'waiting_on_human' | 'needs_human' | 'paused' | 'stopped' | 'done';

/**
 * ChunkSummary
 *
 * One row of the fleet chunk list — derived status + current node.
 *
 * ``current_node_name`` is the node's human graph name (``build``, ``review``) the
 * board renders in place of the raw ``nd_`` ULID; null when the chunk has no
 * current node or its pinned graph cannot resolve the id.
 *
 * Deliberately status-only: the summary feeds the board **card**, which is a passive
 * status view (issue #42), so no operator *fact* is carried here. The pause fact — and
 * every other fact an operator action keys on — reaches the chunk detail dock through
 * :class:`ChunkDetail`, the one place a board action lives. ``runner_id`` (the live
 * route's holder, null when unrouted) is a passive where-is-it fact in that same
 * sense — it lets the fleet registry list each runner's claims — not an action key.
 * ``environment_count`` (issue #69) is a passive where-is-it *count* in that same
 * spirit: the number of environments the chunk's live route holds, so the fleet registry
 * can sum a runner's slot-bar numerator without the full ``environment_ids`` list (which
 * stays out of scope on this status-only summary, reaching only
 * :class:`ChunkDetail.route`). ``cost`` is the one exception (issue #59): the derived
 * spend total is cheap to carry on every card and is not itself an operator fact, so it
 * rides the summary rather than waiting for the detail fetch.
 */
export type ChunkSummary = {
    /**
     * Chunk Id
     */
    chunk_id: string;
    cost?: ChunkUsageTotalView;
    /**
     * Current Node Id
     */
    current_node_id: string | null;
    /**
     * Current Node Name
     */
    current_node_name?: string | null;
    /**
     * Environment Count
     */
    environment_count?: number;
    /**
     * Graph Id
     */
    graph_id: string;
    /**
     * Model
     */
    model: string;
    /**
     * Pm Pointers
     */
    pm_pointers?: Array<PmPointerView>;
    /**
     * Runner Id
     */
    runner_id?: string | null;
    status: ChunkStatus;
};

/**
 * ChunkUsageTotalView
 *
 * A chunk's derived usage/cost total — summed over every recorded invocation
 * (issue #59). Never a stored column: computed at read time by
 * ``derive_chunk_usage``.
 *
 * ``cost_partial`` carries the lower-bound + PARTIAL contract on ``cost_usd`` —
 * see :class:`~blizzard.hub.domain.work.UsageTotal` for the one canonical
 * statement of it, which this view's fields mirror verbatim.
 */
export type ChunkUsageTotalView = {
    /**
     * Cache Create Tokens
     */
    cache_create_tokens: number;
    /**
     * Cache Read Tokens
     */
    cache_read_tokens: number;
    /**
     * Cost Partial
     */
    cost_partial: boolean;
    /**
     * Cost Usd
     */
    cost_usd: number;
    /**
     * Input Tokens
     */
    input_tokens: number;
    /**
     * Output Tokens
     */
    output_tokens: number;
};

/**
 * ChunkUsageView
 *
 * One node-step's usage/cost telemetry (issue #59) — one harness invocation's
 * tokens-by-class and cost, oldest first on :class:`ChunkDetail`.
 *
 * ``cost_usd`` is ``None`` exactly when no result envelope existed for this
 * invocation (the envelope-less transcript-summation fallback) — never fabricated.
 */
export type ChunkUsageView = {
    /**
     * Cache Create Tokens
     */
    cache_create_tokens: number;
    /**
     * Cache Read Tokens
     */
    cache_read_tokens: number;
    /**
     * Cost Usd
     */
    cost_usd: number | null;
    /**
     * Epoch
     */
    epoch: number;
    /**
     * Input Tokens
     */
    input_tokens: number;
    /**
     * Kind
     */
    kind: string;
    /**
     * Model
     */
    model: string;
    /**
     * Node Id
     */
    node_id: string;
    /**
     * Output Tokens
     */
    output_tokens: number;
};

/**
 * CompletionSubmission
 *
 * A node-step's completion — judgement choice + checks + artifacts + epoch.
 */
export type CompletionSubmission = {
    /**
     * Artifacts
     */
    artifacts?: Array<SubmittedArtifact>;
    /**
     * Check Results
     */
    check_results?: Array<CheckResult>;
    /**
     * Choice
     */
    choice: string;
    /**
     * Decision Id
     */
    decision_id?: string | null;
    /**
     * Epoch
     */
    epoch: number;
    /**
     * From Node Id
     */
    from_node_id: string;
    /**
     * Route Token
     */
    route_token?: string | null;
    /**
     * Runner Id
     */
    runner_id: string;
};

/**
 * DecisionChoiceModel
 *
 * One selectable gate outcome — a button on the board/bot.
 */
export type DecisionChoiceModel = {
    /**
     * Description
     */
    description: string;
    /**
     * Name
     */
    name: string;
};

/**
 * DecisionResolutionRequest
 *
 * A person's choice for an open decision — first-write-wins CAS.
 */
export type DecisionResolutionRequest = {
    /**
     * Choice
     */
    choice: string;
    /**
     * Resolved By
     */
    resolved_by?: string;
};

/**
 * DecisionResolutionResponse
 *
 * The winning resolution — the choice, who, and when.
 */
export type DecisionResolutionResponse = {
    /**
     * Choice
     */
    choice: string;
    /**
     * Decision Id
     */
    decision_id: string;
    /**
     * Resolved At
     */
    resolved_at: string;
    /**
     * Resolved By
     */
    resolved_by: string;
};

/**
 * DecisionSubmission
 *
 * A runner-config gate: submit a decision in place of a transition.
 *
 * Carries the gated step's artifacts and its fencing epoch — one atomic, epoch-fenced
 * write, exactly where a worker-judged node would have submitted its transition. The
 * node's choice set is supplied by the hub from the pinned graph, not sent here.
 */
export type DecisionSubmission = {
    /**
     * Artifacts
     */
    artifacts?: Array<SubmittedArtifact>;
    /**
     * Epoch
     */
    epoch: number;
    /**
     * From Node Id
     */
    from_node_id: string;
    /**
     * Route Token
     */
    route_token?: string | null;
    /**
     * Runner Id
     */
    runner_id: string;
};

/**
 * DecisionView
 *
 * A gate decision in full — the board's card and the runner's pickup.
 *
 * ``resolved_choice`` is set once a person has decided; ``transitioned`` is true once
 * the holding runner has recorded the resolving transition. The runner acts on a
 * decision that is resolved but not yet transitioned.
 */
export type DecisionView = {
    /**
     * Choices
     */
    choices?: Array<DecisionChoiceModel>;
    /**
     * Chunk Id
     */
    chunk_id: string;
    /**
     * Decision Id
     */
    decision_id: string;
    /**
     * Epoch
     */
    epoch: number;
    /**
     * Node Id
     */
    node_id: string;
    /**
     * Node Name
     */
    node_name: string;
    /**
     * Resolved At
     */
    resolved_at?: string | null;
    /**
     * Resolved By
     */
    resolved_by?: string | null;
    /**
     * Resolved Choice
     */
    resolved_choice?: string | null;
    /**
     * Submitted At
     */
    submitted_at: string;
    /**
     * Transitioned
     */
    transitioned?: boolean;
};

/**
 * EnvelopeArtifact
 *
 * One artifact carried into a node-step, resolved latest-by-epoch.
 */
export type EnvelopeArtifact = {
    /**
     * Branch Name
     */
    branch_name?: string | null;
    /**
     * Commit Hash
     */
    commit_hash?: string | null;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Epoch
     */
    epoch: number;
    kind: ArtifactKind;
    /**
     * Name
     */
    name: string;
    /**
     * Node Name
     */
    node_name: string;
    /**
     * Repo
     */
    repo?: string | null;
};

/**
 * EnvelopeChoice
 *
 * A selectable outcome the worker's judgement may emit.
 */
export type EnvelopeChoice = {
    /**
     * Description
     */
    description: string;
    /**
     * Name
     */
    name: string;
};

/**
 * EscalationReport
 *
 * A runner's ``escalation.recorded`` — retries exhausted for the node.
 *
 * ``takeover_command`` is the literal ``cd <workdir> && <harness resume>`` a human
 * pastes to enter the parked session; ``epoch`` is the
 * exhausted attempt's fence, closed by a later lease mint.
 */
export type EscalationReport = {
    /**
     * Epoch
     */
    epoch: number;
    /**
     * Runner Id
     */
    runner_id: string;
    /**
     * Takeover Command
     */
    takeover_command?: string;
};

/**
 * EscalationView
 *
 * An open escalation on a ``needs_human`` chunk.
 *
 * Surfaces the runner-composed takeover command so a human can resume the parked
 * session. Present only while the escalation is open —
 * a later lease mint (requeue/takeover) supersedes it and this drops away.
 */
export type EscalationView = {
    /**
     * Epoch
     */
    epoch: number;
    /**
     * Takeover Command
     */
    takeover_command: string;
};

/**
 * Executor
 *
 * Where a node's step runs.
 */
export type Executor = 'runner' | 'hub';

/**
 * FleetSpendView
 *
 * The fleet's usage/cost total since ``since``. ``cost_partial`` carries the
 * lower-bound + PARTIAL contract on ``cost_usd`` — see
 * :class:`~blizzard.hub.domain.work.UsageTotal` for the one canonical statement of
 * it, which this view's fields mirror verbatim.
 */
export type FleetSpendView = {
    /**
     * Cache Create Tokens
     */
    cache_create_tokens: number;
    /**
     * Cache Read Tokens
     */
    cache_read_tokens: number;
    /**
     * Cost Partial
     */
    cost_partial: boolean;
    /**
     * Cost Usd
     */
    cost_usd: number;
    /**
     * Input Tokens
     */
    input_tokens: number;
    /**
     * Output Tokens
     */
    output_tokens: number;
    /**
     * Since
     */
    since: string;
};

/**
 * GraphChoiceView
 *
 * One selectable outcome of a node's judgement.
 */
export type GraphChoiceView = {
    /**
     * Choice Id
     */
    choice_id: string;
    /**
     * Description
     */
    description: string;
    /**
     * Name
     */
    name: string;
};

/**
 * GraphEdgeView
 *
 * A directed, choice-keyed connection between two nodes of one graph.
 */
export type GraphEdgeView = {
    /**
     * Choice Id
     */
    choice_id: string;
    /**
     * From Node Id
     */
    from_node_id: string;
    /**
     * Prompt Addendum
     */
    prompt_addendum?: string | null;
    /**
     * To Node Name
     */
    to_node_name: string;
};

/**
 * GraphLifecycleRequest
 *
 * Retire or re-enable a graph — records who flipped it (issue #101).
 */
export type GraphLifecycleRequest = {
    /**
     * By
     */
    by?: string;
};

/**
 * GraphMintRequest
 *
 * A graph definition to mint — the raw YAML body.
 */
export type GraphMintRequest = {
    /**
     * Definition Yaml
     */
    definition_yaml: string;
};

/**
 * GraphNodeView
 *
 * A reified node in a minted graph — the full immutable definition.
 */
export type GraphNodeView = {
    /**
     * Checks
     */
    checks?: Array<string>;
    /**
     * Choices
     */
    choices?: Array<GraphChoiceView>;
    /**
     * Executor
     */
    executor: string;
    /**
     * Judged By
     */
    judged_by: string;
    /**
     * Judgement Prompt
     */
    judgement_prompt?: string | null;
    /**
     * Mode
     */
    mode?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Node Id
     */
    node_id: string;
    /**
     * Produces
     */
    produces?: Array<string>;
    /**
     * Prompt
     */
    prompt?: string | null;
    /**
     * Retries Exhausted
     */
    retries_exhausted?: string | null;
    /**
     * Retries Max
     */
    retries_max?: number | null;
    /**
     * Session
     */
    session: string;
};

/**
 * GraphSummaryView
 *
 * One graph's summary row — a name-lineage entry as served by ``GET /graphs``.
 *
 * ``effective`` is the newest **non-retired** graph of this ``name`` (issue #101);
 * ``retired`` is this graph's own lifecycle state, independent of ``effective`` — a
 * retired graph is never effective, but a non-retired, non-effective graph is merely
 * superseded by a newer version of the same name.
 */
export type GraphSummaryView = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Effective
     */
    effective: boolean;
    /**
     * Entry Node Id
     */
    entry_node_id: string;
    /**
     * Graph Id
     */
    graph_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Retired
     */
    retired?: boolean;
};

/**
 * GraphView
 *
 * A minted graph as served by ``GET /graphs/{graph_id}`` and the mint response.
 *
 * ``enabled`` is ``not retired`` — the graph's own lifecycle state (issue #101),
 * independent of whether it is currently the newest of its name. ``retired`` is the
 * same fact spelled out explicitly for a board that wants to distinguish "retired"
 * from "merely superseded by a newer version" (:class:`GraphSummaryView`'s
 * ``effective``). Deliberately two wire fields for one fact, not drift: the only
 * constructor, :func:`~blizzard.hub.api.graphs._graph_view`, sets both from the same
 * ``retired`` bool in one call (``enabled=not retired, retired=retired``) — there is
 * no second call site that could set one and forget the other.
 */
export type GraphView = {
    /**
     * Edges
     */
    edges?: Array<GraphEdgeView>;
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Entry Node Id
     */
    entry_node_id: string;
    /**
     * Graph Id
     */
    graph_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Nodes
     */
    nodes?: Array<GraphNodeView>;
    /**
     * Retired
     */
    retired?: boolean;
    /**
     * Warnings
     */
    warnings?: Array<string>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HubAdvanceResponse
 *
 * The result of one on-demand ``POST /api/fleet/chunks/{id}/hub-advance`` (#65,
 * moved under the fleet router by #87).
 *
 * A generic hub command node runs ``run:`` to completion, one call at a time,
 * behind the fleet-wide serialization slot: ``ran=False`` means the slot was held
 * by a different chunk and this call deferred without touching anything — not an
 * error, just try again on a later poll.
 */
export type HubAdvanceResponse = {
    /**
     * Chunk Id
     */
    chunk_id: string;
    /**
     * Detail
     */
    detail?: string;
    /**
     * Outcome Choice
     */
    outcome_choice?: string | null;
    /**
     * Ran
     */
    ran: boolean;
    status: ChunkStatus;
    /**
     * To Node Name
     */
    to_node_name?: string | null;
};

/**
 * HubMarkerRequest
 *
 * The mid-run marker callback's body (#65) — mirrors ``blizzard runner ask``'s
 * own worker-facing callback shape.
 */
export type HubMarkerRequest = {
    /**
     * Content
     */
    content?: string;
    /**
     * Name
     */
    name: string;
};

/**
 * HubMarkerResponse
 *
 * The recorded marker — ``recorded=False`` iff it already existed (idempotent).
 */
export type HubMarkerResponse = {
    /**
     * Chunk Id
     */
    chunk_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Recorded
     */
    recorded: boolean;
};

/**
 * JudgedBy
 *
 * Who renders a node's exit judgement — the structural gate marker.
 */
export type JudgedBy = 'worker' | 'human';

/**
 * LeaseMintReport
 *
 * A runner's ``lease.minted`` — one node-step attempt's fencing epoch.
 */
export type LeaseMintReport = {
    /**
     * Epoch
     */
    epoch: number;
    /**
     * Runner Id
     */
    runner_id: string;
};

/**
 * MigrationView
 *
 * One cross-graph migration step in a chunk's history (issue #90).
 *
 * A judgement choice targeting another graph ends the chunk's attempt in ``from_graph``
 * and re-queues it at ``landed_node`` in ``to_graph`` — its own step in the timeline,
 * never a transition (``bzh:migration-not-transition``). The board renders it as a
 * graph-to-graph hop: ``from_graph/from_node --choice--> to_graph/landed_node``. Node and
 * graph names are resolved server-side against each side's own graph (null when
 * unresolvable); ``model`` is the re-pinned model, or null when the chunk kept its own.
 */
export type MigrationView = {
    /**
     * Choice Name
     */
    choice_name?: string | null;
    /**
     * From Graph Id
     */
    from_graph_id: string;
    /**
     * From Graph Name
     */
    from_graph_name?: string | null;
    /**
     * From Node Id
     */
    from_node_id: string | null;
    /**
     * From Node Name
     */
    from_node_name?: string | null;
    /**
     * Landed Node Id
     */
    landed_node_id?: string | null;
    /**
     * Landed Node Name
     */
    landed_node_name?: string | null;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Recorded At
     */
    recorded_at: string;
    /**
     * To Graph Id
     */
    to_graph_id: string;
    /**
     * To Graph Name
     */
    to_graph_name?: string | null;
};

/**
 * NodeConfig
 *
 * The node's invariant identity for this step.
 */
export type NodeConfig = {
    /**
     * Checks
     */
    checks?: Array<string>;
    /**
     * Choices
     */
    choices?: Array<EnvelopeChoice>;
    executor: Executor;
    judged_by: JudgedBy;
    /**
     * Mode
     */
    mode?: string | null;
    /**
     * Node Id
     */
    node_id: string;
    /**
     * Node Name
     */
    node_name: string;
    /**
     * Produces
     */
    produces?: Array<string>;
    /**
     * Retries Max
     */
    retries_max?: number | null;
    session: SessionMode;
};

/**
 * NodeEnvelope
 *
 * Everything a runner needs to work one node-step.
 */
export type NodeEnvelope = {
    /**
     * Artifacts
     */
    artifacts?: Array<EnvelopeArtifact>;
    /**
     * Chunk Id
     */
    chunk_id: string;
    /**
     * Epoch
     */
    epoch: number;
    /**
     * Graph Id
     */
    graph_id: string;
    /**
     * Judgement Prompt
     */
    judgement_prompt: string | null;
    node: NodeConfig;
    /**
     * Pm Pointers
     */
    pm_pointers?: Array<{
        [key: string]: string;
    }>;
    /**
     * Prompt
     */
    prompt: string | null;
};

/**
 * OpenDecisionsResponse
 *
 * The fleet's open (unresolved) decisions — ``blizzard hub decisions``.
 */
export type OpenDecisionsResponse = {
    /**
     * Decisions
     */
    decisions?: Array<DecisionView>;
};

/**
 * PauseView
 *
 * An open pause on a chunk (issue #46) — who set it and when.
 *
 * Present only while ``paused=True`` is the newest pause fact; a resume clears it.
 * Carried independently of ``status``: PAUSED sits below the human-gated statuses in
 * the derivation order, so a chunk both paused and parked on a question derives
 * ``waiting_on_human`` — this field is the only way the runner (and the board) learn
 * the chunk is paused in that case, and it also answers "who paused it".
 */
export type PauseView = {
    /**
     * By
     */
    by: string;
    /**
     * Set At
     */
    set_at: string;
};

/**
 * PendingView
 *
 * A hub node's in-progress poll (#66) — waiting on external state, honestly.
 *
 * Surfaced on chunk detail so a ``delivering`` chunk parked at a hub node reads
 * truthfully whether it is about to run its first attempt or already mid-poll, and
 * when the next attempt is due — never itself a status (the chunk still derives
 * ``delivering``, mirroring ``awaiting_external_merge``).
 */
export type PendingView = {
    /**
     * Next Poll At
     */
    next_poll_at: string;
    /**
     * Node Name
     */
    node_name: string;
};

/**
 * PmItemEntry
 *
 * One pointer's pass-through PM item — title, body + comment
 * thread, vendor-native.
 *
 * ``label``/``web_url`` are the board-legible pointer label (``blizzard#8``) and its
 * browser address — both null when no configured source names ``source``. A
 * per-pointer forge failure degrades here rather than failing the whole read:
 * ``error`` carries the reason and ``title``/``body`` are null, so one unreachable
 * pointer never blinds the reader to the pointers it did reach.
 */
export type PmItemEntry = {
    /**
     * Body
     */
    body?: string | null;
    /**
     * Comments
     */
    comments?: Array<string>;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Fetched At
     */
    fetched_at: string;
    /**
     * Label
     */
    label?: string | null;
    /**
     * Ref
     */
    ref: string;
    /**
     * Source
     */
    source: string;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Web Url
     */
    web_url?: string | null;
};

/**
 * PmItemsView
 *
 * A chunk's pass-through PM items — one entry per pointer, order preserved.
 *
 * Empty when the chunk holds no pointers — the board's empty state; a grouped chunk carrying
 * many pointers yields one entry per pointer, each fetched fresh and never stored.
 */
export type PmItemsView = {
    /**
     * Items
     */
    items?: Array<PmItemEntry>;
};

/**
 * PmPointerModel
 *
 * One ``{source, ref}`` PM pointer — ``source`` names a configured
 * ``[[pm_source]]``; ``ref`` is that source's own item token.
 */
export type PmPointerModel = {
    /**
     * Ref
     */
    ref: string;
    /**
     * Source
     */
    source: string;
};

/**
 * PmPointerView
 *
 * A pointer as the views render it — the raw pair plus its legible
 * label and browser URL, both rendered by the pointer's configured source binding.
 *
 * ``label`` is the board-legible ``{name}#{ref}`` (e.g. ``blizzard#8``); ``web_url``
 * is its browser-openable address. Both null when no configured source names
 * ``source`` — the board then leans on the chunk's stable short id instead.
 */
export type PmPointerView = {
    /**
     * Label
     */
    label?: string | null;
    /**
     * Ref
     */
    ref: string;
    /**
     * Source
     */
    source: string;
    /**
     * Web Url
     */
    web_url?: string | null;
};

/**
 * PrView
 *
 * An open PR a chunk is parked on in open-pr delivery mode.
 */
export type PrView = {
    /**
     * Number
     */
    number: number;
    /**
     * Repo
     */
    repo: string;
    /**
     * Url
     */
    url: string;
};

/**
 * QuestionAsked
 *
 * A ``question.asked`` fact the runner forwards to the hub.
 *
 * ``question_id`` is runner-minted (``qn_<ulid>``) so the runner can poll the answer
 * back by it; ``epoch`` is the parked lease's fence, ``session_id`` the dormant
 * session to resume around the answer, and ``options`` the choices the board renders.
 */
export type QuestionAsked = {
    /**
     * Asked At
     */
    asked_at: string;
    /**
     * Chunk Id
     */
    chunk_id: string;
    /**
     * Epoch
     */
    epoch: number;
    /**
     * Node Id
     */
    node_id?: string | null;
    /**
     * Options
     */
    options?: Array<string>;
    /**
     * Question
     */
    question: string;
    /**
     * Question Id
     */
    question_id: string;
    /**
     * Runner Id
     */
    runner_id: string;
    /**
     * Session Id
     */
    session_id?: string | null;
};

/**
 * QuestionView
 *
 * A question row with its derived answer state — the surfacing shape.
 *
 * Behind ``GET /questions`` (open only), ``GET /questions/{id}`` (the runner's answer
 * poll), and the chunk detail's open-questions list. ``answered`` and the answer
 * fields derive from the presence of the answer row.
 */
export type QuestionView = {
    /**
     * Answer
     */
    answer?: string | null;
    /**
     * Answered
     */
    answered?: boolean;
    /**
     * Answered At
     */
    answered_at?: string | null;
    /**
     * Answered By
     */
    answered_by?: string | null;
    /**
     * Asked At
     */
    asked_at: string;
    /**
     * Chunk Id
     */
    chunk_id: string;
    /**
     * Epoch
     */
    epoch: number;
    /**
     * Node Id
     */
    node_id?: string | null;
    /**
     * Options
     */
    options?: Array<string>;
    /**
     * Question
     */
    question: string;
    /**
     * Question Id
     */
    question_id: string;
    /**
     * Runner Id
     */
    runner_id: string;
    /**
     * Session Id
     */
    session_id?: string | null;
};

/**
 * QueuePeekEntry
 *
 * One ready chunk, in queue order.
 */
export type QueuePeekEntry = {
    /**
     * Chunk Id
     */
    chunk_id: string;
    /**
     * Graph Id
     */
    graph_id: string;
    /**
     * Pm Pointers
     */
    pm_pointers?: Array<PmPointerModel>;
    /**
     * Position
     */
    position: number;
};

/**
 * QueuePeekResponse
 *
 * The ready queue as peeked by FILL, in the hub's explicit order.
 */
export type QueuePeekResponse = {
    /**
     * Entries
     */
    entries?: Array<QueuePeekEntry>;
};

/**
 * QueueReorderRequest
 *
 * Move a ready chunk to a queue position — the board's Prioritize control.
 *
 * ``position`` is the target index in the ready queue, ``0`` being the top; it is
 * clamped into range, so ``0`` always means "to the front". Ordering is a hub-side
 * property: the move appends one position fact and the order re-derives.
 */
export type QueueReorderRequest = {
    /**
     * Chunk Id
     */
    chunk_id: string;
    /**
     * Position
     */
    position?: number;
};

/**
 * QueueReorderResponse
 *
 * The ready queue after a reorder, in its new order — the board re-renders from it.
 */
export type QueueReorderResponse = {
    /**
     * Entries
     */
    entries?: Array<QueuePeekEntry>;
};

/**
 * ReadinessResponse
 *
 * The wire shape of a readiness reading (openapi-ts consumes this).
 */
export type ReadinessResponse = {
    /**
     * Detail
     */
    detail: string;
    /**
     * Expected Revision
     */
    expected_revision: string | null;
    /**
     * Ready
     */
    ready: boolean;
    /**
     * Store Reachable
     */
    store_reachable: boolean;
    /**
     * Store Revision
     */
    store_revision: string | null;
};

/**
 * RouteClaim
 *
 * A complete route fact posted by the claiming runner.
 */
export type RouteClaim = {
    /**
     * Chunk Id
     */
    chunk_id: string;
    /**
     * Environment Ids
     */
    environment_ids: Array<string>;
    /**
     * Runner Id
     */
    runner_id: string;
    /**
     * Workspace Id
     */
    workspace_id: string;
};

/**
 * RouteClaimResponse
 *
 * The winning claim's reply — the route, its first node envelope, and the
 * route's plaintext capability token (issue #84a), returned exactly once here. The
 * runner stashes it and presents it on every subsequent chunk-scoped write.
 */
export type RouteClaimResponse = {
    /**
     * Chunk Id
     */
    chunk_id: string;
    envelope: NodeEnvelope;
    /**
     * Environment Ids
     */
    environment_ids: Array<string>;
    /**
     * Route Token
     */
    route_token: string;
    /**
     * Runner Id
     */
    runner_id: string;
    /**
     * Workspace Id
     */
    workspace_id: string;
};

/**
 * RouteTokenRekeyResponse
 *
 * ``POST /api/fleet/chunks/{id}/route-token``'s reply — a fresh plaintext route
 * capability token for the chunk's live route (issue #84b), returned exactly once
 * here, same as the claim response's own ``route_token``. Covers the
 * crash-after-mint-before-response case: the holding runner re-keys rather than
 * being permanently locked out of a token it never read back.
 */
export type RouteTokenRekeyResponse = {
    /**
     * Chunk Id
     */
    chunk_id: string;
    /**
     * Route Token
     */
    route_token: string;
};

/**
 * RouteView
 *
 * A chunk's route — where it is being worked.
 */
export type RouteView = {
    /**
     * Environment Ids
     */
    environment_ids?: Array<string>;
    /**
     * Runner Id
     */
    runner_id: string;
    /**
     * Workspace Id
     */
    workspace_id: string;
};

/**
 * RunnerEnrollmentResponse
 *
 * A freshly minted (or rotated) bearer token — issue #86a.
 *
 * ``token`` is the plaintext; the hub keeps only its sha256 hash from here on, so
 * this response is the one and only place it is ever visible again. A re-enroll
 * call rotates: the old token stops resolving the moment this response lands.
 */
export type RunnerEnrollmentResponse = {
    /**
     * Runner Id
     */
    runner_id: string;
    /**
     * Token
     */
    token: string;
};

/**
 * RunnerFact
 *
 * One buffered runner fact: its per-runner seq, its kind, and its payload.
 *
 * ``payload`` is the kind-specific body — for ``lease.minted`` ``{chunk_id, epoch,
 * route_token}``, for ``escalation.recorded`` ``{chunk_id, epoch, takeover_command,
 * route_token}``, for ``question.asked`` the ask fields plus ``route_token`` — kept
 * open so a new runner fact kind bolts on without a wire change. ``route_token``
 * (issue #84a) is the chunk-scoped fact's route capability token, stamped at
 * enqueue; present-only in this phase (the hub does not yet reject on it).
 */
export type RunnerFact = {
    /**
     * Kind
     */
    kind: string;
    /**
     * Payload
     */
    payload?: {
        [key: string]: unknown;
    };
    /**
     * Seq
     */
    seq: number;
};

/**
 * RunnerFactAck
 *
 * The hub's per-batch acknowledgement against its high-water mark.
 *
 * ``high_water`` is the runner's new mark after this batch; ``applied`` and
 * ``already_applied`` partition the pushed seqs so the runner can ack its buffer
 * (a semantic rejection still acks — rejection is an outcome, not a delivery
 * failure). ``rejected`` names seqs the hub refused for a non-idempotency
 * reason (an unknown kind), which the runner surfaces rather than silently drops.
 */
export type RunnerFactAck = {
    /**
     * Already Applied
     */
    already_applied?: Array<number>;
    /**
     * Applied
     */
    applied?: Array<number>;
    /**
     * High Water
     */
    high_water: number;
    /**
     * Rejected
     */
    rejected?: Array<number>;
    /**
     * Runner Id
     */
    runner_id: string;
};

/**
 * RunnerFactBatch
 *
 * A runner's push of one-or-more buffered facts, ordered by seq.
 */
export type RunnerFactBatch = {
    /**
     * Facts
     */
    facts: Array<RunnerFact>;
    /**
     * Runner Id
     */
    runner_id: string;
};

/**
 * RunnerListResponse
 *
 * The fleet registry — every registered runner with its liveness.
 */
export type RunnerListResponse = {
    /**
     * Runners
     */
    runners?: Array<RunnerView>;
};

/**
 * RunnerPauseRequest
 *
 * Set a runner's pause brake — records who flipped it.
 */
export type RunnerPauseRequest = {
    /**
     * By
     */
    by?: string;
};

/**
 * RunnerRegistrationRequest
 *
 * Register a runner into the fleet — runner id + workspace binding.
 *
 * ``env_capacity`` is the runner's configured environment-pool size (the length of its
 * ``workspace_envs``) — the denominator the board's slot bar renders ``used/total``
 * against. Absent (``None``) from an older runner binary that predates this field, in
 * which case the hub stores/reports null and the board omits the bar rather than
 * guessing a total. Re-registration is the runner's heartbeat, so a ``workspace_envs``
 * change converges on the next pull (the stored value is overwritten unconditionally).
 */
export type RunnerRegistrationRequest = {
    /**
     * Env Capacity
     */
    env_capacity?: number | null;
    /**
     * Runner Id
     */
    runner_id: string;
    /**
     * Workspace Id
     */
    workspace_id: string;
};

/**
 * RunnerRegistrationResponse
 *
 * The registered runner's id, and whether this call first created its row.
 */
export type RunnerRegistrationResponse = {
    /**
     * First Registration
     */
    first_registration: boolean;
    /**
     * Runner Id
     */
    runner_id: string;
};

/**
 * RunnerView
 *
 * One fleet-registry row — derived liveness and both brakes.
 *
 * A runner can be paused by two different parties for two different reasons, so the two
 * are reported separately rather than collapsed into one ``paused`` (issue #43): the
 * board shows *which*. A reader that wants "is it claiming?" ORs them; since issue #45
 * the two diverge past claiming — ``hub_paused`` keeps its claims-only meaning, while
 * ``locally_paused`` alone answers "is it spawning anything at all?".
 */
export type RunnerView = {
    /**
     * Env Capacity
     */
    env_capacity?: number | null;
    /**
     * Hub Paused
     */
    hub_paused: boolean;
    /**
     * Last Seen At
     */
    last_seen_at: string;
    /**
     * Locally Paused
     */
    locally_paused?: boolean;
    /**
     * Locally Paused By
     */
    locally_paused_by?: string | null;
    /**
     * Locally Paused Reason
     */
    locally_paused_reason?: string | null;
    /**
     * Online
     */
    online: boolean;
    /**
     * Registered At
     */
    registered_at: string;
    /**
     * Runner Id
     */
    runner_id: string;
    /**
     * Workspace Id
     */
    workspace_id: string;
};

/**
 * SessionMode
 *
 * Per-node session freshness.
 */
export type SessionMode = 'resume' | 'fresh';

/**
 * SubmittedArtifact
 *
 * An artifact committed atomically with the completion.
 */
export type SubmittedArtifact = {
    /**
     * Attached
     */
    attached?: boolean;
    /**
     * Branch Name
     */
    branch_name?: string | null;
    /**
     * Commit Hash
     */
    commit_hash?: string | null;
    /**
     * Content
     */
    content?: string | null;
    kind: ArtifactKind;
    /**
     * Name
     */
    name: string;
    /**
     * Repo
     */
    repo?: string | null;
};

/**
 * TransitionView
 *
 * One accepted transition in a chunk's history.
 *
 * The edge a node-step took — its origin node, the judgement choice that routed it,
 * and its destination — oldest first on the detail. This is what makes the review-fail
 * loop legible: a ``review -> build`` entry with ``choice_name = "fail"`` is a visible
 * step in the timeline (MVP criterion 9/11).
 *
 * ``from_node_name``/``to_node_name`` are the nodes' human graph names (``build``,
 * ``review``) the board renders in place of the raw ``nd_`` ULIDs; resolved here so the
 * timeline is legible without reassembly, null when the pinned graph cannot
 * resolve the id.
 *
 * ``graph_id``/``graph_name`` identify the graph this step happened in (issue #90) —
 * resolved per-transition against its own graph, so a chunk that later migrated still
 * labels its old-graph steps with the graph they belong to rather than the current pin;
 * both null for a step predating graph-provenance (never backfilled with a name).
 */
export type TransitionView = {
    /**
     * Choice Name
     */
    choice_name: string | null;
    /**
     * Epoch
     */
    epoch: number;
    /**
     * From Node Id
     */
    from_node_id: string | null;
    /**
     * From Node Name
     */
    from_node_name?: string | null;
    /**
     * Graph Id
     */
    graph_id?: string | null;
    /**
     * Graph Name
     */
    graph_name?: string | null;
    /**
     * Recorded At
     */
    recorded_at: string;
    /**
     * To Node Id
     */
    to_node_id: string;
    /**
     * To Node Name
     */
    to_node_name?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ListChunksApiChunksGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/chunks';
};

export type ListChunksApiChunksGetResponses = {
    /**
     * Response List Chunks Api Chunks Get
     *
     * Successful Response
     */
    200: Array<ChunkSummary>;
};

export type ListChunksApiChunksGetResponse = ListChunksApiChunksGetResponses[keyof ListChunksApiChunksGetResponses];

export type IngestChunkApiChunksPostData = {
    body: ChunkIngestRequest;
    path?: never;
    query?: never;
    url: '/api/chunks';
};

export type IngestChunkApiChunksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IngestChunkApiChunksPostError = IngestChunkApiChunksPostErrors[keyof IngestChunkApiChunksPostErrors];

export type IngestChunkApiChunksPostResponses = {
    /**
     * Successful Response
     */
    201: ChunkIngestResponse;
};

export type IngestChunkApiChunksPostResponse = IngestChunkApiChunksPostResponses[keyof IngestChunkApiChunksPostResponses];

export type GetChunkApiChunksChunkIdGetData = {
    body?: never;
    path: {
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query?: never;
    url: '/api/chunks/{chunk_id}';
};

export type GetChunkApiChunksChunkIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChunkApiChunksChunkIdGetError = GetChunkApiChunksChunkIdGetErrors[keyof GetChunkApiChunksChunkIdGetErrors];

export type GetChunkApiChunksChunkIdGetResponses = {
    /**
     * Successful Response
     */
    200: ChunkDetail;
};

export type GetChunkApiChunksChunkIdGetResponse = GetChunkApiChunksChunkIdGetResponses[keyof GetChunkApiChunksChunkIdGetResponses];

export type DetachChunkApiChunksChunkIdDetachPostData = {
    body?: never;
    path: {
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query?: never;
    url: '/api/chunks/{chunk_id}/detach';
};

export type DetachChunkApiChunksChunkIdDetachPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DetachChunkApiChunksChunkIdDetachPostError = DetachChunkApiChunksChunkIdDetachPostErrors[keyof DetachChunkApiChunksChunkIdDetachPostErrors];

export type DetachChunkApiChunksChunkIdDetachPostResponses = {
    /**
     * Response Detach Chunk Api Chunks  Chunk Id  Detach Post
     *
     * Successful Response
     */
    202: {
        [key: string]: string;
    };
};

export type DetachChunkApiChunksChunkIdDetachPostResponse = DetachChunkApiChunksChunkIdDetachPostResponses[keyof DetachChunkApiChunksChunkIdDetachPostResponses];

export type SetChunkGraphApiChunksChunkIdGraphPostData = {
    body: ChunkGraphUpdateRequest;
    path: {
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query?: never;
    url: '/api/chunks/{chunk_id}/graph';
};

export type SetChunkGraphApiChunksChunkIdGraphPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetChunkGraphApiChunksChunkIdGraphPostError = SetChunkGraphApiChunksChunkIdGraphPostErrors[keyof SetChunkGraphApiChunksChunkIdGraphPostErrors];

export type SetChunkGraphApiChunksChunkIdGraphPostResponses = {
    /**
     * Successful Response
     */
    202: ChunkGraphView;
};

export type SetChunkGraphApiChunksChunkIdGraphPostResponse = SetChunkGraphApiChunksChunkIdGraphPostResponses[keyof SetChunkGraphApiChunksChunkIdGraphPostResponses];

export type GroupChunksApiChunksChunkIdGroupPostData = {
    body: ChunkGroupRequest;
    path: {
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query?: never;
    url: '/api/chunks/{chunk_id}/group';
};

export type GroupChunksApiChunksChunkIdGroupPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GroupChunksApiChunksChunkIdGroupPostError = GroupChunksApiChunksChunkIdGroupPostErrors[keyof GroupChunksApiChunksChunkIdGroupPostErrors];

export type GroupChunksApiChunksChunkIdGroupPostResponses = {
    /**
     * Successful Response
     */
    200: ChunkGroupResponse;
};

export type GroupChunksApiChunksChunkIdGroupPostResponse = GroupChunksApiChunksChunkIdGroupPostResponses[keyof GroupChunksApiChunksChunkIdGroupPostResponses];

export type RecordHubMarkerApiChunksChunkIdHubMarkersPostData = {
    body: HubMarkerRequest;
    path: {
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query: {
        /**
         * Node Id
         */
        node_id: string;
        /**
         * Epoch
         */
        epoch: number;
    };
    url: '/api/chunks/{chunk_id}/hub-markers';
};

export type RecordHubMarkerApiChunksChunkIdHubMarkersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecordHubMarkerApiChunksChunkIdHubMarkersPostError = RecordHubMarkerApiChunksChunkIdHubMarkersPostErrors[keyof RecordHubMarkerApiChunksChunkIdHubMarkersPostErrors];

export type RecordHubMarkerApiChunksChunkIdHubMarkersPostResponses = {
    /**
     * Successful Response
     */
    200: HubMarkerResponse;
};

export type RecordHubMarkerApiChunksChunkIdHubMarkersPostResponse = RecordHubMarkerApiChunksChunkIdHubMarkersPostResponses[keyof RecordHubMarkerApiChunksChunkIdHubMarkersPostResponses];

export type SetChunkModelApiChunksChunkIdModelPostData = {
    body: ChunkModelUpdateRequest;
    path: {
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query?: never;
    url: '/api/chunks/{chunk_id}/model';
};

export type SetChunkModelApiChunksChunkIdModelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetChunkModelApiChunksChunkIdModelPostError = SetChunkModelApiChunksChunkIdModelPostErrors[keyof SetChunkModelApiChunksChunkIdModelPostErrors];

export type SetChunkModelApiChunksChunkIdModelPostResponses = {
    /**
     * Successful Response
     */
    202: ChunkModelView;
};

export type SetChunkModelApiChunksChunkIdModelPostResponse = SetChunkModelApiChunksChunkIdModelPostResponses[keyof SetChunkModelApiChunksChunkIdModelPostResponses];

export type PauseChunkApiChunksChunkIdPausePostData = {
    body: ChunkPauseRequest;
    path: {
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query?: never;
    url: '/api/chunks/{chunk_id}/pause';
};

export type PauseChunkApiChunksChunkIdPausePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PauseChunkApiChunksChunkIdPausePostError = PauseChunkApiChunksChunkIdPausePostErrors[keyof PauseChunkApiChunksChunkIdPausePostErrors];

export type PauseChunkApiChunksChunkIdPausePostResponses = {
    /**
     * Response Pause Chunk Api Chunks  Chunk Id  Pause Post
     *
     * Successful Response
     */
    202: {
        [key: string]: string;
    };
};

export type PauseChunkApiChunksChunkIdPausePostResponse = PauseChunkApiChunksChunkIdPausePostResponses[keyof PauseChunkApiChunksChunkIdPausePostResponses];

export type GetPmItemsApiChunksChunkIdPmItemsGetData = {
    body?: never;
    path: {
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query?: never;
    url: '/api/chunks/{chunk_id}/pm-items';
};

export type GetPmItemsApiChunksChunkIdPmItemsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPmItemsApiChunksChunkIdPmItemsGetError = GetPmItemsApiChunksChunkIdPmItemsGetErrors[keyof GetPmItemsApiChunksChunkIdPmItemsGetErrors];

export type GetPmItemsApiChunksChunkIdPmItemsGetResponses = {
    /**
     * Successful Response
     */
    200: PmItemsView;
};

export type GetPmItemsApiChunksChunkIdPmItemsGetResponse = GetPmItemsApiChunksChunkIdPmItemsGetResponses[keyof GetPmItemsApiChunksChunkIdPmItemsGetResponses];

export type PromoteChunkApiChunksChunkIdPromotePostData = {
    body?: never;
    path: {
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query?: never;
    url: '/api/chunks/{chunk_id}/promote';
};

export type PromoteChunkApiChunksChunkIdPromotePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PromoteChunkApiChunksChunkIdPromotePostError = PromoteChunkApiChunksChunkIdPromotePostErrors[keyof PromoteChunkApiChunksChunkIdPromotePostErrors];

export type PromoteChunkApiChunksChunkIdPromotePostResponses = {
    /**
     * Response Promote Chunk Api Chunks  Chunk Id  Promote Post
     *
     * Successful Response
     */
    202: {
        [key: string]: string;
    };
};

export type PromoteChunkApiChunksChunkIdPromotePostResponse = PromoteChunkApiChunksChunkIdPromotePostResponses[keyof PromoteChunkApiChunksChunkIdPromotePostResponses];

export type RequeueChunkApiChunksChunkIdRequeuesPostData = {
    body?: never;
    path: {
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query?: never;
    url: '/api/chunks/{chunk_id}/requeues';
};

export type RequeueChunkApiChunksChunkIdRequeuesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RequeueChunkApiChunksChunkIdRequeuesPostError = RequeueChunkApiChunksChunkIdRequeuesPostErrors[keyof RequeueChunkApiChunksChunkIdRequeuesPostErrors];

export type RequeueChunkApiChunksChunkIdRequeuesPostResponses = {
    /**
     * Response Requeue Chunk Api Chunks  Chunk Id  Requeues Post
     *
     * Successful Response
     */
    202: {
        [key: string]: string;
    };
};

export type RequeueChunkApiChunksChunkIdRequeuesPostResponse = RequeueChunkApiChunksChunkIdRequeuesPostResponses[keyof RequeueChunkApiChunksChunkIdRequeuesPostResponses];

export type ResumeChunkApiChunksChunkIdResumePostData = {
    body: ChunkPauseRequest;
    path: {
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query?: never;
    url: '/api/chunks/{chunk_id}/resume';
};

export type ResumeChunkApiChunksChunkIdResumePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumeChunkApiChunksChunkIdResumePostError = ResumeChunkApiChunksChunkIdResumePostErrors[keyof ResumeChunkApiChunksChunkIdResumePostErrors];

export type ResumeChunkApiChunksChunkIdResumePostResponses = {
    /**
     * Response Resume Chunk Api Chunks  Chunk Id  Resume Post
     *
     * Successful Response
     */
    202: {
        [key: string]: string;
    };
};

export type ResumeChunkApiChunksChunkIdResumePostResponse = ResumeChunkApiChunksChunkIdResumePostResponses[keyof ResumeChunkApiChunksChunkIdResumePostResponses];

export type ListDecisionsApiDecisionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/decisions';
};

export type ListDecisionsApiDecisionsGetResponses = {
    /**
     * Successful Response
     */
    200: OpenDecisionsResponse;
};

export type ListDecisionsApiDecisionsGetResponse = ListDecisionsApiDecisionsGetResponses[keyof ListDecisionsApiDecisionsGetResponses];

export type ResolveDecisionApiDecisionsDecisionIdResolutionPostData = {
    body: DecisionResolutionRequest;
    path: {
        /**
         * Decision Id
         */
        decision_id: string;
    };
    query?: never;
    url: '/api/decisions/{decision_id}/resolution';
};

export type ResolveDecisionApiDecisionsDecisionIdResolutionPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResolveDecisionApiDecisionsDecisionIdResolutionPostError = ResolveDecisionApiDecisionsDecisionIdResolutionPostErrors[keyof ResolveDecisionApiDecisionsDecisionIdResolutionPostErrors];

export type ResolveDecisionApiDecisionsDecisionIdResolutionPostResponses = {
    /**
     * Successful Response
     */
    200: DecisionResolutionResponse;
};

export type ResolveDecisionApiDecisionsDecisionIdResolutionPostResponse = ResolveDecisionApiDecisionsDecisionIdResolutionPostResponses[keyof ResolveDecisionApiDecisionsDecisionIdResolutionPostResponses];

export type GetChunkApiFleetChunksChunkIdGetData = {
    body?: never;
    path: {
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query?: never;
    url: '/api/fleet/chunks/{chunk_id}';
};

export type GetChunkApiFleetChunksChunkIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChunkApiFleetChunksChunkIdGetError = GetChunkApiFleetChunksChunkIdGetErrors[keyof GetChunkApiFleetChunksChunkIdGetErrors];

export type GetChunkApiFleetChunksChunkIdGetResponses = {
    /**
     * Successful Response
     */
    200: ChunkDetail;
};

export type GetChunkApiFleetChunksChunkIdGetResponse = GetChunkApiFleetChunksChunkIdGetResponses[keyof GetChunkApiFleetChunksChunkIdGetResponses];

export type SubmitCompletionApiFleetChunksChunkIdCompletionsPostData = {
    body: CompletionSubmission;
    path: {
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query?: never;
    url: '/api/fleet/chunks/{chunk_id}/completions';
};

export type SubmitCompletionApiFleetChunksChunkIdCompletionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitCompletionApiFleetChunksChunkIdCompletionsPostError = SubmitCompletionApiFleetChunksChunkIdCompletionsPostErrors[keyof SubmitCompletionApiFleetChunksChunkIdCompletionsPostErrors];

export type SubmitCompletionApiFleetChunksChunkIdCompletionsPostResponses = {
    /**
     * Successful Response
     */
    200: ApplyResponse;
};

export type SubmitCompletionApiFleetChunksChunkIdCompletionsPostResponse = SubmitCompletionApiFleetChunksChunkIdCompletionsPostResponses[keyof SubmitCompletionApiFleetChunksChunkIdCompletionsPostResponses];

export type SubmitDecisionApiFleetChunksChunkIdDecisionsPostData = {
    body: DecisionSubmission;
    path: {
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query?: never;
    url: '/api/fleet/chunks/{chunk_id}/decisions';
};

export type SubmitDecisionApiFleetChunksChunkIdDecisionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitDecisionApiFleetChunksChunkIdDecisionsPostError = SubmitDecisionApiFleetChunksChunkIdDecisionsPostErrors[keyof SubmitDecisionApiFleetChunksChunkIdDecisionsPostErrors];

export type SubmitDecisionApiFleetChunksChunkIdDecisionsPostResponses = {
    /**
     * Successful Response
     */
    200: ApplyResponse;
};

export type SubmitDecisionApiFleetChunksChunkIdDecisionsPostResponse = SubmitDecisionApiFleetChunksChunkIdDecisionsPostResponses[keyof SubmitDecisionApiFleetChunksChunkIdDecisionsPostResponses];

export type GetEnvelopeApiFleetChunksChunkIdEnvelopeGetData = {
    body?: never;
    path: {
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query?: never;
    url: '/api/fleet/chunks/{chunk_id}/envelope';
};

export type GetEnvelopeApiFleetChunksChunkIdEnvelopeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEnvelopeApiFleetChunksChunkIdEnvelopeGetError = GetEnvelopeApiFleetChunksChunkIdEnvelopeGetErrors[keyof GetEnvelopeApiFleetChunksChunkIdEnvelopeGetErrors];

export type GetEnvelopeApiFleetChunksChunkIdEnvelopeGetResponses = {
    /**
     * Successful Response
     */
    200: NodeEnvelope;
};

export type GetEnvelopeApiFleetChunksChunkIdEnvelopeGetResponse = GetEnvelopeApiFleetChunksChunkIdEnvelopeGetResponses[keyof GetEnvelopeApiFleetChunksChunkIdEnvelopeGetResponses];

export type ReportEscalationApiFleetChunksChunkIdEscalationsPostData = {
    body: EscalationReport;
    path: {
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query?: never;
    url: '/api/fleet/chunks/{chunk_id}/escalations';
};

export type ReportEscalationApiFleetChunksChunkIdEscalationsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReportEscalationApiFleetChunksChunkIdEscalationsPostError = ReportEscalationApiFleetChunksChunkIdEscalationsPostErrors[keyof ReportEscalationApiFleetChunksChunkIdEscalationsPostErrors];

export type ReportEscalationApiFleetChunksChunkIdEscalationsPostResponses = {
    /**
     * Response Report Escalation Api Fleet Chunks  Chunk Id  Escalations Post
     *
     * Successful Response
     */
    202: {
        [key: string]: string;
    };
};

export type ReportEscalationApiFleetChunksChunkIdEscalationsPostResponse = ReportEscalationApiFleetChunksChunkIdEscalationsPostResponses[keyof ReportEscalationApiFleetChunksChunkIdEscalationsPostResponses];

export type HubAdvanceApiFleetChunksChunkIdHubAdvancePostData = {
    body?: never;
    path: {
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query?: never;
    url: '/api/fleet/chunks/{chunk_id}/hub-advance';
};

export type HubAdvanceApiFleetChunksChunkIdHubAdvancePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HubAdvanceApiFleetChunksChunkIdHubAdvancePostError = HubAdvanceApiFleetChunksChunkIdHubAdvancePostErrors[keyof HubAdvanceApiFleetChunksChunkIdHubAdvancePostErrors];

export type HubAdvanceApiFleetChunksChunkIdHubAdvancePostResponses = {
    /**
     * Successful Response
     */
    200: HubAdvanceResponse;
};

export type HubAdvanceApiFleetChunksChunkIdHubAdvancePostResponse = HubAdvanceApiFleetChunksChunkIdHubAdvancePostResponses[keyof HubAdvanceApiFleetChunksChunkIdHubAdvancePostResponses];

export type ReportLeaseApiFleetChunksChunkIdLeasesPostData = {
    body: LeaseMintReport;
    path: {
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query?: never;
    url: '/api/fleet/chunks/{chunk_id}/leases';
};

export type ReportLeaseApiFleetChunksChunkIdLeasesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReportLeaseApiFleetChunksChunkIdLeasesPostError = ReportLeaseApiFleetChunksChunkIdLeasesPostErrors[keyof ReportLeaseApiFleetChunksChunkIdLeasesPostErrors];

export type ReportLeaseApiFleetChunksChunkIdLeasesPostResponses = {
    /**
     * Response Report Lease Api Fleet Chunks  Chunk Id  Leases Post
     *
     * Successful Response
     */
    202: {
        [key: string]: string;
    };
};

export type ReportLeaseApiFleetChunksChunkIdLeasesPostResponse = ReportLeaseApiFleetChunksChunkIdLeasesPostResponses[keyof ReportLeaseApiFleetChunksChunkIdLeasesPostResponses];

export type GetPmItemsApiFleetChunksChunkIdPmItemsGetData = {
    body?: never;
    path: {
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query?: never;
    url: '/api/fleet/chunks/{chunk_id}/pm-items';
};

export type GetPmItemsApiFleetChunksChunkIdPmItemsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPmItemsApiFleetChunksChunkIdPmItemsGetError = GetPmItemsApiFleetChunksChunkIdPmItemsGetErrors[keyof GetPmItemsApiFleetChunksChunkIdPmItemsGetErrors];

export type GetPmItemsApiFleetChunksChunkIdPmItemsGetResponses = {
    /**
     * Successful Response
     */
    200: PmItemsView;
};

export type GetPmItemsApiFleetChunksChunkIdPmItemsGetResponse = GetPmItemsApiFleetChunksChunkIdPmItemsGetResponses[keyof GetPmItemsApiFleetChunksChunkIdPmItemsGetResponses];

export type RekeyRouteTokenApiFleetChunksChunkIdRouteTokenPostData = {
    body?: never;
    path: {
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query?: never;
    url: '/api/fleet/chunks/{chunk_id}/route-token';
};

export type RekeyRouteTokenApiFleetChunksChunkIdRouteTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RekeyRouteTokenApiFleetChunksChunkIdRouteTokenPostError = RekeyRouteTokenApiFleetChunksChunkIdRouteTokenPostErrors[keyof RekeyRouteTokenApiFleetChunksChunkIdRouteTokenPostErrors];

export type RekeyRouteTokenApiFleetChunksChunkIdRouteTokenPostResponses = {
    /**
     * Successful Response
     */
    200: RouteTokenRekeyResponse;
};

export type RekeyRouteTokenApiFleetChunksChunkIdRouteTokenPostResponse = RekeyRouteTokenApiFleetChunksChunkIdRouteTokenPostResponses[keyof RekeyRouteTokenApiFleetChunksChunkIdRouteTokenPostResponses];

export type IngestRunnerFactsApiFleetEventsPostData = {
    body: RunnerFactBatch;
    path?: never;
    query?: never;
    url: '/api/fleet/events';
};

export type IngestRunnerFactsApiFleetEventsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IngestRunnerFactsApiFleetEventsPostError = IngestRunnerFactsApiFleetEventsPostErrors[keyof IngestRunnerFactsApiFleetEventsPostErrors];

export type IngestRunnerFactsApiFleetEventsPostResponses = {
    /**
     * Successful Response
     */
    200: RunnerFactAck;
};

export type IngestRunnerFactsApiFleetEventsPostResponse = IngestRunnerFactsApiFleetEventsPostResponses[keyof IngestRunnerFactsApiFleetEventsPostResponses];

export type GetQuestionApiFleetQuestionsQuestionIdGetData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/api/fleet/questions/{question_id}';
};

export type GetQuestionApiFleetQuestionsQuestionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQuestionApiFleetQuestionsQuestionIdGetError = GetQuestionApiFleetQuestionsQuestionIdGetErrors[keyof GetQuestionApiFleetQuestionsQuestionIdGetErrors];

export type GetQuestionApiFleetQuestionsQuestionIdGetResponses = {
    /**
     * Successful Response
     */
    200: QuestionView;
};

export type GetQuestionApiFleetQuestionsQuestionIdGetResponse = GetQuestionApiFleetQuestionsQuestionIdGetResponses[keyof GetQuestionApiFleetQuestionsQuestionIdGetResponses];

export type PeekQueueApiFleetQueuePeekGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/fleet/queue/peek';
};

export type PeekQueueApiFleetQueuePeekGetResponses = {
    /**
     * Successful Response
     */
    200: QueuePeekResponse;
};

export type PeekQueueApiFleetQueuePeekGetResponse = PeekQueueApiFleetQueuePeekGetResponses[keyof PeekQueueApiFleetQueuePeekGetResponses];

export type ClaimRouteApiFleetRoutesPostData = {
    body: RouteClaim;
    path?: never;
    query?: never;
    url: '/api/fleet/routes';
};

export type ClaimRouteApiFleetRoutesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ClaimRouteApiFleetRoutesPostError = ClaimRouteApiFleetRoutesPostErrors[keyof ClaimRouteApiFleetRoutesPostErrors];

export type ClaimRouteApiFleetRoutesPostResponses = {
    /**
     * Successful Response
     */
    201: RouteClaimResponse;
};

export type ClaimRouteApiFleetRoutesPostResponse = ClaimRouteApiFleetRoutesPostResponses[keyof ClaimRouteApiFleetRoutesPostResponses];

export type RegisterRunnerApiFleetRunnersPostData = {
    body: RunnerRegistrationRequest;
    path?: never;
    query?: never;
    url: '/api/fleet/runners';
};

export type RegisterRunnerApiFleetRunnersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterRunnerApiFleetRunnersPostError = RegisterRunnerApiFleetRunnersPostErrors[keyof RegisterRunnerApiFleetRunnersPostErrors];

export type RegisterRunnerApiFleetRunnersPostResponses = {
    /**
     * Successful Response
     */
    201: RunnerRegistrationResponse;
};

export type RegisterRunnerApiFleetRunnersPostResponse = RegisterRunnerApiFleetRunnersPostResponses[keyof RegisterRunnerApiFleetRunnersPostResponses];

export type GetRunnerApiFleetRunnersRunnerIdGetData = {
    body?: never;
    path: {
        /**
         * Runner Id
         */
        runner_id: string;
    };
    query?: never;
    url: '/api/fleet/runners/{runner_id}';
};

export type GetRunnerApiFleetRunnersRunnerIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRunnerApiFleetRunnersRunnerIdGetError = GetRunnerApiFleetRunnersRunnerIdGetErrors[keyof GetRunnerApiFleetRunnersRunnerIdGetErrors];

export type GetRunnerApiFleetRunnersRunnerIdGetResponses = {
    /**
     * Successful Response
     */
    200: RunnerView;
};

export type GetRunnerApiFleetRunnersRunnerIdGetResponse = GetRunnerApiFleetRunnersRunnerIdGetResponses[keyof GetRunnerApiFleetRunnersRunnerIdGetResponses];

export type HeartbeatRunnerApiFleetRunnersRunnerIdHeartbeatsPostData = {
    body?: never;
    path: {
        /**
         * Runner Id
         */
        runner_id: string;
    };
    query?: never;
    url: '/api/fleet/runners/{runner_id}/heartbeats';
};

export type HeartbeatRunnerApiFleetRunnersRunnerIdHeartbeatsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HeartbeatRunnerApiFleetRunnersRunnerIdHeartbeatsPostError = HeartbeatRunnerApiFleetRunnersRunnerIdHeartbeatsPostErrors[keyof HeartbeatRunnerApiFleetRunnersRunnerIdHeartbeatsPostErrors];

export type HeartbeatRunnerApiFleetRunnersRunnerIdHeartbeatsPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type HeartbeatRunnerApiFleetRunnersRunnerIdHeartbeatsPostResponse = HeartbeatRunnerApiFleetRunnersRunnerIdHeartbeatsPostResponses[keyof HeartbeatRunnerApiFleetRunnersRunnerIdHeartbeatsPostResponses];

export type ListGraphsApiGraphsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/graphs';
};

export type ListGraphsApiGraphsGetResponses = {
    /**
     * Response List Graphs Api Graphs Get
     *
     * Successful Response
     */
    200: Array<GraphSummaryView>;
};

export type ListGraphsApiGraphsGetResponse = ListGraphsApiGraphsGetResponses[keyof ListGraphsApiGraphsGetResponses];

export type MintGraphApiGraphsPostData = {
    body: GraphMintRequest;
    path?: never;
    query?: never;
    url: '/api/graphs';
};

export type MintGraphApiGraphsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MintGraphApiGraphsPostError = MintGraphApiGraphsPostErrors[keyof MintGraphApiGraphsPostErrors];

export type MintGraphApiGraphsPostResponses = {
    /**
     * Successful Response
     */
    201: GraphView;
};

export type MintGraphApiGraphsPostResponse = MintGraphApiGraphsPostResponses[keyof MintGraphApiGraphsPostResponses];

export type GetGraphApiGraphsGraphIdGetData = {
    body?: never;
    path: {
        /**
         * Graph Id
         */
        graph_id: string;
    };
    query?: never;
    url: '/api/graphs/{graph_id}';
};

export type GetGraphApiGraphsGraphIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGraphApiGraphsGraphIdGetError = GetGraphApiGraphsGraphIdGetErrors[keyof GetGraphApiGraphsGraphIdGetErrors];

export type GetGraphApiGraphsGraphIdGetResponses = {
    /**
     * Successful Response
     */
    200: GraphView;
};

export type GetGraphApiGraphsGraphIdGetResponse = GetGraphApiGraphsGraphIdGetResponses[keyof GetGraphApiGraphsGraphIdGetResponses];

export type EnableGraphApiGraphsGraphIdEnablePostData = {
    body: GraphLifecycleRequest;
    path: {
        /**
         * Graph Id
         */
        graph_id: string;
    };
    query?: never;
    url: '/api/graphs/{graph_id}/enable';
};

export type EnableGraphApiGraphsGraphIdEnablePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EnableGraphApiGraphsGraphIdEnablePostError = EnableGraphApiGraphsGraphIdEnablePostErrors[keyof EnableGraphApiGraphsGraphIdEnablePostErrors];

export type EnableGraphApiGraphsGraphIdEnablePostResponses = {
    /**
     * Successful Response
     */
    202: GraphView;
};

export type EnableGraphApiGraphsGraphIdEnablePostResponse = EnableGraphApiGraphsGraphIdEnablePostResponses[keyof EnableGraphApiGraphsGraphIdEnablePostResponses];

export type RetireGraphApiGraphsGraphIdRetirePostData = {
    body: GraphLifecycleRequest;
    path: {
        /**
         * Graph Id
         */
        graph_id: string;
    };
    query?: never;
    url: '/api/graphs/{graph_id}/retire';
};

export type RetireGraphApiGraphsGraphIdRetirePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RetireGraphApiGraphsGraphIdRetirePostError = RetireGraphApiGraphsGraphIdRetirePostErrors[keyof RetireGraphApiGraphsGraphIdRetirePostErrors];

export type RetireGraphApiGraphsGraphIdRetirePostResponses = {
    /**
     * Successful Response
     */
    202: GraphView;
};

export type RetireGraphApiGraphsGraphIdRetirePostResponse = RetireGraphApiGraphsGraphIdRetirePostResponses[keyof RetireGraphApiGraphsGraphIdRetirePostResponses];

export type HealthApiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthApiHealthGetResponses = {
    /**
     * Response Health Api Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthApiHealthGetResponse = HealthApiHealthGetResponses[keyof HealthApiHealthGetResponses];

export type ListOpenQuestionsApiQuestionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/questions';
};

export type ListOpenQuestionsApiQuestionsGetResponses = {
    /**
     * Response List Open Questions Api Questions Get
     *
     * Successful Response
     */
    200: Array<QuestionView>;
};

export type ListOpenQuestionsApiQuestionsGetResponse = ListOpenQuestionsApiQuestionsGetResponses[keyof ListOpenQuestionsApiQuestionsGetResponses];

export type AskQuestionApiQuestionsPostData = {
    body: QuestionAsked;
    path?: never;
    query?: never;
    url: '/api/questions';
};

export type AskQuestionApiQuestionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AskQuestionApiQuestionsPostError = AskQuestionApiQuestionsPostErrors[keyof AskQuestionApiQuestionsPostErrors];

export type AskQuestionApiQuestionsPostResponses = {
    /**
     * Response Ask Question Api Questions Post
     *
     * Successful Response
     */
    201: {
        [key: string]: string;
    };
};

export type AskQuestionApiQuestionsPostResponse = AskQuestionApiQuestionsPostResponses[keyof AskQuestionApiQuestionsPostResponses];

export type AnswerQuestionApiQuestionsQuestionIdAnswerPostData = {
    body: AnswerRequest;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/api/questions/{question_id}/answer';
};

export type AnswerQuestionApiQuestionsQuestionIdAnswerPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnswerQuestionApiQuestionsQuestionIdAnswerPostError = AnswerQuestionApiQuestionsQuestionIdAnswerPostErrors[keyof AnswerQuestionApiQuestionsQuestionIdAnswerPostErrors];

export type AnswerQuestionApiQuestionsQuestionIdAnswerPostResponses = {
    /**
     * Successful Response
     */
    201: AnswerResult;
};

export type AnswerQuestionApiQuestionsQuestionIdAnswerPostResponse = AnswerQuestionApiQuestionsQuestionIdAnswerPostResponses[keyof AnswerQuestionApiQuestionsQuestionIdAnswerPostResponses];

export type PeekQueueApiQueuePeekGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/queue/peek';
};

export type PeekQueueApiQueuePeekGetResponses = {
    /**
     * Successful Response
     */
    200: QueuePeekResponse;
};

export type PeekQueueApiQueuePeekGetResponse = PeekQueueApiQueuePeekGetResponses[keyof PeekQueueApiQueuePeekGetResponses];

export type ReorderQueueApiQueueReorderPostData = {
    body: QueueReorderRequest;
    path?: never;
    query?: never;
    url: '/api/queue/reorder';
};

export type ReorderQueueApiQueueReorderPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReorderQueueApiQueueReorderPostError = ReorderQueueApiQueueReorderPostErrors[keyof ReorderQueueApiQueueReorderPostErrors];

export type ReorderQueueApiQueueReorderPostResponses = {
    /**
     * Successful Response
     */
    200: QueueReorderResponse;
};

export type ReorderQueueApiQueueReorderPostResponse = ReorderQueueApiQueueReorderPostResponses[keyof ReorderQueueApiQueueReorderPostResponses];

export type ReadyApiReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ready';
};

export type ReadyApiReadyGetResponses = {
    /**
     * Successful Response
     */
    200: ReadinessResponse;
};

export type ReadyApiReadyGetResponse = ReadyApiReadyGetResponses[keyof ReadyApiReadyGetResponses];

export type ListRunnersApiRunnersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/runners';
};

export type ListRunnersApiRunnersGetResponses = {
    /**
     * Successful Response
     */
    200: RunnerListResponse;
};

export type ListRunnersApiRunnersGetResponse = ListRunnersApiRunnersGetResponses[keyof ListRunnersApiRunnersGetResponses];

export type EnrollRunnerApiRunnersRunnerIdEnrollmentsPostData = {
    body?: never;
    path: {
        /**
         * Runner Id
         */
        runner_id: string;
    };
    query?: never;
    url: '/api/runners/{runner_id}/enrollments';
};

export type EnrollRunnerApiRunnersRunnerIdEnrollmentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EnrollRunnerApiRunnersRunnerIdEnrollmentsPostError = EnrollRunnerApiRunnersRunnerIdEnrollmentsPostErrors[keyof EnrollRunnerApiRunnersRunnerIdEnrollmentsPostErrors];

export type EnrollRunnerApiRunnersRunnerIdEnrollmentsPostResponses = {
    /**
     * Successful Response
     */
    201: RunnerEnrollmentResponse;
};

export type EnrollRunnerApiRunnersRunnerIdEnrollmentsPostResponse = EnrollRunnerApiRunnersRunnerIdEnrollmentsPostResponses[keyof EnrollRunnerApiRunnersRunnerIdEnrollmentsPostResponses];

export type PauseRunnerApiRunnersRunnerIdPausePostData = {
    body: RunnerPauseRequest;
    path: {
        /**
         * Runner Id
         */
        runner_id: string;
    };
    query?: never;
    url: '/api/runners/{runner_id}/pause';
};

export type PauseRunnerApiRunnersRunnerIdPausePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PauseRunnerApiRunnersRunnerIdPausePostError = PauseRunnerApiRunnersRunnerIdPausePostErrors[keyof PauseRunnerApiRunnersRunnerIdPausePostErrors];

export type PauseRunnerApiRunnersRunnerIdPausePostResponses = {
    /**
     * Successful Response
     */
    200: RunnerView;
};

export type PauseRunnerApiRunnersRunnerIdPausePostResponse = PauseRunnerApiRunnersRunnerIdPausePostResponses[keyof PauseRunnerApiRunnersRunnerIdPausePostResponses];

export type ResumeRunnerApiRunnersRunnerIdResumePostData = {
    body: RunnerPauseRequest;
    path: {
        /**
         * Runner Id
         */
        runner_id: string;
    };
    query?: never;
    url: '/api/runners/{runner_id}/resume';
};

export type ResumeRunnerApiRunnersRunnerIdResumePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumeRunnerApiRunnersRunnerIdResumePostError = ResumeRunnerApiRunnersRunnerIdResumePostErrors[keyof ResumeRunnerApiRunnersRunnerIdResumePostErrors];

export type ResumeRunnerApiRunnersRunnerIdResumePostResponses = {
    /**
     * Successful Response
     */
    200: RunnerView;
};

export type ResumeRunnerApiRunnersRunnerIdResumePostResponse = ResumeRunnerApiRunnersRunnerIdResumePostResponses[keyof ResumeRunnerApiRunnersRunnerIdResumePostResponses];

export type FleetSpendApiSpendGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Since
         */
        since: string;
    };
    url: '/api/spend';
};

export type FleetSpendApiSpendGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FleetSpendApiSpendGetError = FleetSpendApiSpendGetErrors[keyof FleetSpendApiSpendGetErrors];

export type FleetSpendApiSpendGetResponses = {
    /**
     * Successful Response
     */
    200: FleetSpendView;
};

export type FleetSpendApiSpendGetResponse = FleetSpendApiSpendGetResponses[keyof FleetSpendApiSpendGetResponses];
