"""Export the hub and runner OpenAPI specs to a stable path.

The Angular apps consume a TypeScript client generated by openapi-ts from these
specs (``bzh:generated-client``); the generated client is committed, and CI's
drift check regenerates and fails on any uncommitted difference. This exporter is
the single source of both specs: it builds each app from throwaway config (no
store, no server) and dumps a deterministic, sorted JSON so the drift check is
stable.

    blizzard-export-openapi --out-dir openapi

writes ``openapi/hub.openapi.json`` and ``openapi/runner.openapi.json``.
"""

from __future__ import annotations

import json
from pathlib import Path

import click

from blizzard.hub.app import create_app_for_export as build_hub_app
from blizzard.runner.app import create_app_for_export as build_runner_app

SPECS = (
    ("hub", build_hub_app),
    ("runner", build_runner_app),
)


def export(out_dir: Path) -> list[Path]:
    """Write both specs into ``out_dir``; return the written paths."""
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for name, build in SPECS:
        spec = build().openapi()
        path = out_dir / f"{name}.openapi.json"
        path.write_text(json.dumps(spec, indent=2, sort_keys=True) + "\n")
        written.append(path)
    return written


@click.command()
@click.option(
    "--out-dir",
    default="openapi",
    type=click.Path(file_okay=False, path_type=Path),
    help="Directory to write the OpenAPI JSON specs into.",
)
def main(out_dir: Path) -> None:
    """Dump the hub and runner OpenAPI specs for client generation and drift checks."""
    for path in export(out_dir):
        click.echo(f"wrote {path}")


if __name__ == "__main__":
    main()
