# yaml-language-server: $schema=https://raw.githubusercontent.com/ast-grep/ast-grep/main/schemas/sgconfig.json

ruleDirs:
  - contracts/ast-grep/rules
testConfigs:
  - testDir: contracts/ast-grep/rule-tests
