// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetPmItemsApiChunksChunkIdPmItemsGetData, GetPmItemsApiChunksChunkIdPmItemsGetErrors, GetPmItemsApiChunksChunkIdPmItemsGetResponses, HealthApiHealthGetData, HealthApiHealthGetResponses, HeartbeatApiHeartbeatPostData, HeartbeatApiHeartbeatPostErrors, HeartbeatApiHeartbeatPostResponses, ListLeasesApiLeasesGetData, ListLeasesApiLeasesGetResponses, PatchRunnerApiRunnerPatchData, PatchRunnerApiRunnerPatchErrors, PatchRunnerApiRunnerPatchResponses, ReadWorkspacePromptApiWorkspacePromptGetData, ReadWorkspacePromptApiWorkspacePromptGetResponses, ReadyApiReadyGetData, ReadyApiReadyGetResponses, RecordAskApiLeasesLeaseIdAsksPostData, RecordAskApiLeasesLeaseIdAsksPostErrors, RecordAskApiLeasesLeaseIdAsksPostResponses, ReplaceWorkspacePromptApiWorkspacePromptPutData, ReplaceWorkspacePromptApiWorkspacePromptPutErrors, ReplaceWorkspacePromptApiWorkspacePromptPutResponses, SessionEndApiLeasesLeaseIdSessionEndPostData, SessionEndApiLeasesLeaseIdSessionEndPostErrors, SessionEndApiLeasesLeaseIdSessionEndPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get Pm Items
 *
 * Forward a chunk's PM-items read to the hub — the layered pass-through (D-084).
 */
export const getPmItemsApiChunksChunkIdPmItemsGet = <ThrowOnError extends boolean = false>(options: Options<GetPmItemsApiChunksChunkIdPmItemsGetData, ThrowOnError>): RequestResult<GetPmItemsApiChunksChunkIdPmItemsGetResponses, GetPmItemsApiChunksChunkIdPmItemsGetErrors, ThrowOnError> => (options.client ?? client).get<GetPmItemsApiChunksChunkIdPmItemsGetResponses, GetPmItemsApiChunksChunkIdPmItemsGetErrors, ThrowOnError>({ url: '/api/chunks/{chunk_id}/pm-items', ...options });

/**
 * Health
 */
export const healthApiHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthApiHealthGetData, ThrowOnError>): RequestResult<HealthApiHealthGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthApiHealthGetResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

/**
 * Heartbeat
 *
 * Record a lease heartbeat, stamped with the injected clock (D-069).
 */
export const heartbeatApiHeartbeatPost = <ThrowOnError extends boolean = false>(options: Options<HeartbeatApiHeartbeatPostData, ThrowOnError>): RequestResult<HeartbeatApiHeartbeatPostResponses, HeartbeatApiHeartbeatPostErrors, ThrowOnError> => (options.client ?? client).post<HeartbeatApiHeartbeatPostResponses, HeartbeatApiHeartbeatPostErrors, ThrowOnError>({
    url: '/api/heartbeat',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Leases
 *
 * Every active lease, derived at read time (issue #28) — local store only.
 */
export const listLeasesApiLeasesGet = <ThrowOnError extends boolean = false>(options?: Options<ListLeasesApiLeasesGetData, ThrowOnError>): RequestResult<ListLeasesApiLeasesGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListLeasesApiLeasesGetResponses, unknown, ThrowOnError>({ url: '/api/leases', ...options });

/**
 * Record Ask
 *
 * Record a worker's ask against its lease, minting the question id ([ask-answer.md]).
 */
export const recordAskApiLeasesLeaseIdAsksPost = <ThrowOnError extends boolean = false>(options: Options<RecordAskApiLeasesLeaseIdAsksPostData, ThrowOnError>): RequestResult<RecordAskApiLeasesLeaseIdAsksPostResponses, RecordAskApiLeasesLeaseIdAsksPostErrors, ThrowOnError> => (options.client ?? client).post<RecordAskApiLeasesLeaseIdAsksPostResponses, RecordAskApiLeasesLeaseIdAsksPostErrors, ThrowOnError>({
    url: '/api/leases/{lease_id}/asks',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Session End
 *
 * Record a lease's session-end, stamped with the injected clock (D-055/D-082).
 */
export const sessionEndApiLeasesLeaseIdSessionEndPost = <ThrowOnError extends boolean = false>(options: Options<SessionEndApiLeasesLeaseIdSessionEndPostData, ThrowOnError>): RequestResult<SessionEndApiLeasesLeaseIdSessionEndPostResponses, SessionEndApiLeasesLeaseIdSessionEndPostErrors, ThrowOnError> => (options.client ?? client).post<SessionEndApiLeasesLeaseIdSessionEndPostResponses, SessionEndApiLeasesLeaseIdSessionEndPostErrors, ThrowOnError>({ url: '/api/leases/{lease_id}/session-end', ...options });

/**
 * Ready
 */
export const readyApiReadyGet = <ThrowOnError extends boolean = false>(options?: Options<ReadyApiReadyGetData, ThrowOnError>): RequestResult<ReadyApiReadyGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ReadyApiReadyGetResponses, unknown, ThrowOnError>({ url: '/api/ready', ...options });

/**
 * Patch Runner
 *
 * Set this runner's own pause brake — it stops claiming; in-flight chunks run on (issue #43).
 *
 * Local to this machine and independent of the hub's brake: it works with the hub
 * unreachable, and it neither reads nor writes the hub's flag.
 */
export const patchRunnerApiRunnerPatch = <ThrowOnError extends boolean = false>(options: Options<PatchRunnerApiRunnerPatchData, ThrowOnError>): RequestResult<PatchRunnerApiRunnerPatchResponses, PatchRunnerApiRunnerPatchErrors, ThrowOnError> => (options.client ?? client).patch<PatchRunnerApiRunnerPatchResponses, PatchRunnerApiRunnerPatchErrors, ThrowOnError>({
    url: '/api/runner',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Workspace Prompt
 *
 * The effective spawn preamble prompt: the runtime override if set, else static config (issue #17).
 */
export const readWorkspacePromptApiWorkspacePromptGet = <ThrowOnError extends boolean = false>(options?: Options<ReadWorkspacePromptApiWorkspacePromptGetData, ThrowOnError>): RequestResult<ReadWorkspacePromptApiWorkspacePromptGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ReadWorkspacePromptApiWorkspacePromptGetResponses, unknown, ThrowOnError>({ url: '/api/workspace-prompt', ...options });

/**
 * Replace Workspace Prompt
 *
 * Replace the runtime workspace-prompt override — effective on subsequent spawns (issue #17).
 */
export const replaceWorkspacePromptApiWorkspacePromptPut = <ThrowOnError extends boolean = false>(options: Options<ReplaceWorkspacePromptApiWorkspacePromptPutData, ThrowOnError>): RequestResult<ReplaceWorkspacePromptApiWorkspacePromptPutResponses, ReplaceWorkspacePromptApiWorkspacePromptPutErrors, ThrowOnError> => (options.client ?? client).put<ReplaceWorkspacePromptApiWorkspacePromptPutResponses, ReplaceWorkspacePromptApiWorkspacePromptPutErrors, ThrowOnError>({
    url: '/api/workspace-prompt',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
