// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AskRequest
 *
 * A worker's ask: the question and its optional pipe-separated choices.
 */
export type AskRequest = {
    /**
     * Options
     */
    options?: Array<string>;
    /**
     * Question
     */
    question: string;
};

/**
 * AskResponse
 *
 * The recorded ask — its minted question id (openapi-ts consumes this).
 */
export type AskResponse = {
    /**
     * Lease Id
     */
    lease_id: string;
    /**
     * Question Id
     */
    question_id: string;
    /**
     * Recorded
     */
    recorded: boolean;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HeartbeatRequest
 *
 * A worker's heartbeat: the lease it inherited at spawn (``BLIZZARD_LEASE_ID``).
 */
export type HeartbeatRequest = {
    /**
     * Lease Id
     */
    lease_id: string;
};

/**
 * HeartbeatResponse
 *
 * The recorded acknowledgement (openapi-ts consumes this).
 */
export type HeartbeatResponse = {
    /**
     * Lease Id
     */
    lease_id: string;
    /**
     * Recorded
     */
    recorded: boolean;
};

/**
 * PmItemView
 *
 * A pass-through PM item read (D-047) — body + comments, vendor-native.
 */
export type PmItemView = {
    /**
     * Body
     */
    body: string;
    /**
     * Comments
     */
    comments?: Array<string>;
    /**
     * Fetched At
     */
    fetched_at: string;
    /**
     * Provider
     */
    provider: string;
    /**
     * Url
     */
    url: string;
};

/**
 * ReadinessResponse
 *
 * The wire shape of a readiness reading (openapi-ts consumes this).
 */
export type ReadinessResponse = {
    /**
     * Detail
     */
    detail: string;
    /**
     * Expected Revision
     */
    expected_revision: string | null;
    /**
     * Ready
     */
    ready: boolean;
    /**
     * Store Reachable
     */
    store_reachable: boolean;
    /**
     * Store Revision
     */
    store_revision: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetPmItemsApiChunksChunkIdPmItemsGetData = {
    body?: never;
    path: {
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query?: never;
    url: '/api/chunks/{chunk_id}/pm-items';
};

export type GetPmItemsApiChunksChunkIdPmItemsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPmItemsApiChunksChunkIdPmItemsGetError = GetPmItemsApiChunksChunkIdPmItemsGetErrors[keyof GetPmItemsApiChunksChunkIdPmItemsGetErrors];

export type GetPmItemsApiChunksChunkIdPmItemsGetResponses = {
    /**
     * Successful Response
     */
    200: PmItemView;
};

export type GetPmItemsApiChunksChunkIdPmItemsGetResponse = GetPmItemsApiChunksChunkIdPmItemsGetResponses[keyof GetPmItemsApiChunksChunkIdPmItemsGetResponses];

export type HealthApiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthApiHealthGetResponses = {
    /**
     * Response Health Api Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthApiHealthGetResponse = HealthApiHealthGetResponses[keyof HealthApiHealthGetResponses];

export type HeartbeatApiHeartbeatPostData = {
    body: HeartbeatRequest;
    path?: never;
    query?: never;
    url: '/api/heartbeat';
};

export type HeartbeatApiHeartbeatPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HeartbeatApiHeartbeatPostError = HeartbeatApiHeartbeatPostErrors[keyof HeartbeatApiHeartbeatPostErrors];

export type HeartbeatApiHeartbeatPostResponses = {
    /**
     * Successful Response
     */
    200: HeartbeatResponse;
};

export type HeartbeatApiHeartbeatPostResponse = HeartbeatApiHeartbeatPostResponses[keyof HeartbeatApiHeartbeatPostResponses];

export type RecordAskApiLeasesLeaseIdAsksPostData = {
    body: AskRequest;
    path: {
        /**
         * Lease Id
         */
        lease_id: string;
    };
    query?: never;
    url: '/api/leases/{lease_id}/asks';
};

export type RecordAskApiLeasesLeaseIdAsksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecordAskApiLeasesLeaseIdAsksPostError = RecordAskApiLeasesLeaseIdAsksPostErrors[keyof RecordAskApiLeasesLeaseIdAsksPostErrors];

export type RecordAskApiLeasesLeaseIdAsksPostResponses = {
    /**
     * Successful Response
     */
    201: AskResponse;
};

export type RecordAskApiLeasesLeaseIdAsksPostResponse = RecordAskApiLeasesLeaseIdAsksPostResponses[keyof RecordAskApiLeasesLeaseIdAsksPostResponses];

export type ReadyApiReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ready';
};

export type ReadyApiReadyGetResponses = {
    /**
     * Successful Response
     */
    200: ReadinessResponse;
};

export type ReadyApiReadyGetResponse = ReadyApiReadyGetResponses[keyof ReadyApiReadyGetResponses];
