// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AskListResponse
 *
 * Every ask still awaiting an answer.
 */
export type AskListResponse = {
    /**
     * Items
     */
    items?: Array<AskView>;
};

/**
 * AskRequest
 *
 * A worker's ask: the question and its optional pipe-separated choices.
 */
export type AskRequest = {
    /**
     * Options
     */
    options?: Array<string>;
    /**
     * Question
     */
    question: string;
};

/**
 * AskResponse
 *
 * The recorded ask — its minted question id (openapi-ts consumes this).
 */
export type AskResponse = {
    /**
     * Lease Id
     */
    lease_id: string;
    /**
     * Question Id
     */
    question_id: string;
    /**
     * Recorded
     */
    recorded: boolean;
};

/**
 * AskView
 *
 * One open ask — ``GET /api/asks?open=true``.
 */
export type AskView = {
    /**
     * Asked At
     */
    asked_at: string;
    /**
     * Chunk Id
     */
    chunk_id: string;
    /**
     * Lease Id
     */
    lease_id: string;
    /**
     * Options
     */
    options?: Array<string>;
    /**
     * Question
     */
    question: string;
    /**
     * Question Id
     */
    question_id: string;
    /**
     * Session Id
     */
    session_id: string | null;
};

/**
 * CapacitiesView
 *
 * Agent slots — the same math FILL claims against.
 */
export type CapacitiesView = {
    /**
     * Free
     */
    free: number;
    /**
     * Max Agents
     */
    max_agents: number;
    /**
     * Used
     */
    used: number;
};

/**
 * EnvironmentListResponse
 *
 * Every environment this runner currently holds.
 */
export type EnvironmentListResponse = {
    /**
     * Items
     */
    items?: Array<HeldEnvironmentView>;
};

/**
 * EscalationListResponse
 *
 * Every escalation still open — no later lease mint has superseded it.
 */
export type EscalationListResponse = {
    /**
     * Items
     */
    items?: Array<EscalationView>;
};

/**
 * EscalationView
 *
 * One parked escalation, carrying its literal takeover command — ``GET /api/escalations``.
 */
export type EscalationView = {
    /**
     * Chunk Id
     */
    chunk_id: string;
    /**
     * Closed At
     */
    closed_at: string;
    /**
     * Epoch
     */
    epoch: number;
    /**
     * Lease Id
     */
    lease_id: string;
    /**
     * Node Id
     */
    node_id: string;
    /**
     * Resume Command
     */
    resume_command: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HeartbeatRequest
 *
 * A worker's heartbeat: the lease it inherited at spawn (``BLIZZARD_LEASE_ID``).
 */
export type HeartbeatRequest = {
    /**
     * Lease Id
     */
    lease_id: string;
};

/**
 * HeartbeatResponse
 *
 * The recorded acknowledgement (openapi-ts consumes this).
 */
export type HeartbeatResponse = {
    /**
     * Lease Id
     */
    lease_id: string;
    /**
     * Recorded
     */
    recorded: boolean;
};

/**
 * HeldEnvironmentView
 *
 * One environment this runner currently holds — ``GET /api/environments``.
 */
export type HeldEnvironmentView = {
    /**
     * Chunk Id
     */
    chunk_id: string;
    /**
     * Environment Id
     */
    environment_id: string;
    /**
     * Held Since
     */
    held_since: string;
};

/**
 * HubConnectivityView
 *
 * Hub reachability (derived, not probed) plus the outbound backlog depth.
 */
export type HubConnectivityView = {
    /**
     * Buffer Depth
     */
    buffer_depth: number;
    /**
     * Last Contact At
     */
    last_contact_at: string | null;
    /**
     * Reachable
     */
    reachable: boolean;
};

/**
 * LeaseListResponse
 *
 * Active leases, then recently-closed ones — the panel's list (issue #28/#29).
 */
export type LeaseListResponse = {
    /**
     * Items
     */
    items?: Array<LeaseView>;
};

/**
 * LeaseView
 *
 * One lease — active or recently-closed — with its joined binding facts and
 * derived state (issue #28; closed leases added issue #29).
 */
export type LeaseView = {
    /**
     * Chunk Id
     */
    chunk_id: string;
    /**
     * Closed At
     */
    closed_at: string | null;
    /**
     * Closure Reason
     */
    closure_reason: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Environment Id
     */
    environment_id: string | null;
    /**
     * Epoch
     */
    epoch: number;
    /**
     * Graph Id
     */
    graph_id: string;
    /**
     * Last Heartbeat At
     */
    last_heartbeat_at: string | null;
    /**
     * Lease Id
     */
    lease_id: string;
    /**
     * Node Id
     */
    node_id: string;
    /**
     * Node Name
     */
    node_name: string;
    /**
     * Pid
     */
    pid: number | null;
    /**
     * Session Id
     */
    session_id: string | null;
    /**
     * State
     */
    state: 'running' | 'stale' | 'parked' | 'spawning' | 'exited' | 'closed';
    /**
     * Workdir
     */
    workdir: string | null;
};

/**
 * OpenTakeoverListResponse
 *
 * Every takeover still open across this runner's held chunks.
 */
export type OpenTakeoverListResponse = {
    /**
     * Items
     */
    items?: Array<OpenTakeoverView>;
};

/**
 * OpenTakeoverView
 *
 * One open operator takeover — ``GET /api/takeovers``, the stranded-takeover
 * recovery surface (issue #52): the chunk it holds, the ``takeover_id`` an
 * interrupted terminal never PATCHed closed, and how long it has been held.
 */
export type OpenTakeoverView = {
    /**
     * Chunk Id
     */
    chunk_id: string;
    /**
     * Held Since
     */
    held_since: string;
    /**
     * Takeover Id
     */
    takeover_id: string;
};

/**
 * PauseStateView
 *
 * The pause brake's two independent surfaces, plus their effective OR.
 */
export type PauseStateView = {
    /**
     * Effective
     */
    effective: boolean;
    /**
     * Hub
     */
    hub: boolean;
    /**
     * Local
     */
    local: boolean;
};

/**
 * PmItemEntry
 *
 * One pointer's pass-through PM item — title, body + comment
 * thread, vendor-native.
 *
 * ``label``/``web_url`` are the board-legible pointer label (``blizzard#8``) and its
 * browser address — both null when no configured source names ``source``. A
 * per-pointer forge failure degrades here rather than failing the whole read:
 * ``error`` carries the reason and ``title``/``body`` are null, so one unreachable
 * pointer never blinds the reader to the pointers it did reach.
 */
export type PmItemEntry = {
    /**
     * Body
     */
    body?: string | null;
    /**
     * Comments
     */
    comments?: Array<string>;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Fetched At
     */
    fetched_at: string;
    /**
     * Label
     */
    label?: string | null;
    /**
     * Ref
     */
    ref: string;
    /**
     * Source
     */
    source: string;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Web Url
     */
    web_url?: string | null;
};

/**
 * PmItemsView
 *
 * A chunk's pass-through PM items — one entry per pointer, order preserved.
 *
 * Empty when the chunk holds no pointers — the board's empty state; a grouped chunk carrying
 * many pointers yields one entry per pointer, each fetched fresh and never stored.
 */
export type PmItemsView = {
    /**
     * Items
     */
    items?: Array<PmItemEntry>;
};

/**
 * ReadinessResponse
 *
 * The wire shape of a readiness reading (openapi-ts consumes this).
 */
export type ReadinessResponse = {
    /**
     * Detail
     */
    detail: string;
    /**
     * Expected Revision
     */
    expected_revision: string | null;
    /**
     * Ready
     */
    ready: boolean;
    /**
     * Store Reachable
     */
    store_reachable: boolean;
    /**
     * Store Revision
     */
    store_revision: string | null;
};

/**
 * RequeueResponse
 *
 * ``POST /chunks/{id}/requeues`` — the local hold is cleared; the next FILL spawns
 * a fresh attempt at the chunk's current node.
 */
export type RequeueResponse = {
    /**
     * Chunk Id
     */
    chunk_id: string;
    /**
     * Requeued
     */
    requeued: boolean;
};

/**
 * RunnerControlPatch
 *
 * Declarative controls on the runner singleton — ``paused`` now, routing knobs post-MVP.
 */
export type RunnerControlPatch = {
    /**
     * By
     */
    by?: string;
    /**
     * Paused
     */
    paused: boolean;
};

/**
 * RunnerControlView
 *
 * The runner singleton's derived pause state (openapi-ts consumes this).
 */
export type RunnerControlView = {
    /**
     * Hub Paused
     */
    hub_paused: boolean;
    /**
     * Local Paused
     */
    local_paused: boolean;
    /**
     * Paused
     */
    paused: boolean;
    /**
     * Runner Id
     */
    runner_id: string;
};

/**
 * RunnerStatusView
 *
 * ``GET /api/runner`` — identity, pause states, capacities, hub connectivity, last tick.
 */
export type RunnerStatusView = {
    capacities: CapacitiesView;
    hub: HubConnectivityView;
    /**
     * Last Tick At
     */
    last_tick_at: string | null;
    pause: PauseStateView;
    /**
     * Runner Id
     */
    runner_id: string;
    /**
     * Workspace Id
     */
    workspace_id: string;
};

/**
 * SelfTestCheckView
 *
 * One check's pass/fail result (openapi-ts consumes this).
 */
export type SelfTestCheckView = {
    /**
     * Detail
     */
    detail: string;
    /**
     * Name
     */
    name: string;
    /**
     * Passed
     */
    passed: boolean;
};

/**
 * SelfTestStartRequest
 *
 * Which coding harness to run the canary against.
 */
export type SelfTestStartRequest = {
    /**
     * Harness
     */
    harness: string;
};

/**
 * SelfTestView
 *
 * A selftest run's current state — ``running`` until every check has resolved.
 */
export type SelfTestView = {
    /**
     * Checks
     */
    checks: Array<SelfTestCheckView>;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Harness
     */
    harness: string;
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: string;
};

/**
 * SessionEndResponse
 *
 * The recorded acknowledgement (openapi-ts consumes this).
 */
export type SessionEndResponse = {
    /**
     * Lease Id
     */
    lease_id: string;
    /**
     * Recorded
     */
    recorded: boolean;
};

/**
 * TakeoverEndResponse
 *
 * ``PATCH /chunks/{id}/takeovers/{tid}`` — the CLI calls this once its child exits.
 */
export type TakeoverEndResponse = {
    /**
     * Ended
     */
    ended: boolean;
    /**
     * Takeover Id
     */
    takeover_id: string;
};

/**
 * TakeoverOpenResponse
 *
 * ``POST /chunks/{id}/takeovers`` — the CLI execs ``command`` verbatim in ``workdir``.
 */
export type TakeoverOpenResponse = {
    /**
     * Command
     */
    command: string;
    /**
     * Takeover Id
     */
    takeover_id: string;
    /**
     * Workdir
     */
    workdir: string;
};

/**
 * TakeoverRequest
 *
 * The takeover request body — ``force`` kills a live worker attempt first.
 */
export type TakeoverRequest = {
    /**
     * Force
     */
    force?: boolean;
};

/**
 * TranscriptResponse
 *
 * A lease's parsed transcript — always 200 when the lease exists.
 */
export type TranscriptResponse = {
    /**
     * Available
     */
    available: boolean;
    /**
     * Lease Id
     */
    lease_id: string;
    /**
     * Reason
     */
    reason: 'spawning' | 'not_found' | 'unreadable' | null;
    /**
     * Session Id
     */
    session_id: string | null;
    /**
     * Truncated
     */
    truncated?: boolean;
    /**
     * Turns
     */
    turns?: Array<TurnView>;
};

/**
 * TurnView
 *
 * One collapsed conversation turn on the wire.
 */
export type TurnView = {
    /**
     * Index
     */
    index: number;
    /**
     * Kind
     */
    kind: 'env' | 'asst' | 'tool';
    /**
     * Text
     */
    text: string;
    /**
     * Timestamp
     */
    timestamp: string | null;
    /**
     * Tool Input
     */
    tool_input: string | null;
    /**
     * Tool Name
     */
    tool_name: string | null;
    /**
     * Tool Output
     */
    tool_output: string | null;
    /**
     * Truncated
     */
    truncated: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * WorkspacePromptReplacement
 *
 * A replacement workspace prompt — applies to subsequent spawns with no restart.
 */
export type WorkspacePromptReplacement = {
    /**
     * Prompt
     */
    prompt: string;
};

/**
 * WorkspacePromptResponse
 *
 * The effective workspace prompt prepended to every worker spawn (openapi-ts consumes this).
 */
export type WorkspacePromptResponse = {
    /**
     * Prompt
     */
    prompt: string;
};

export type ListAsksApiAsksGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Open
         */
        open?: boolean;
    };
    url: '/api/asks';
};

export type ListAsksApiAsksGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAsksApiAsksGetError = ListAsksApiAsksGetErrors[keyof ListAsksApiAsksGetErrors];

export type ListAsksApiAsksGetResponses = {
    /**
     * Successful Response
     */
    200: AskListResponse;
};

export type ListAsksApiAsksGetResponse = ListAsksApiAsksGetResponses[keyof ListAsksApiAsksGetResponses];

export type GetPmItemsApiChunksChunkIdPmItemsGetData = {
    body?: never;
    path: {
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query?: never;
    url: '/api/chunks/{chunk_id}/pm-items';
};

export type GetPmItemsApiChunksChunkIdPmItemsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPmItemsApiChunksChunkIdPmItemsGetError = GetPmItemsApiChunksChunkIdPmItemsGetErrors[keyof GetPmItemsApiChunksChunkIdPmItemsGetErrors];

export type GetPmItemsApiChunksChunkIdPmItemsGetResponses = {
    /**
     * Successful Response
     */
    200: PmItemsView;
};

export type GetPmItemsApiChunksChunkIdPmItemsGetResponse = GetPmItemsApiChunksChunkIdPmItemsGetResponses[keyof GetPmItemsApiChunksChunkIdPmItemsGetResponses];

export type RequeueChunkApiChunksChunkIdRequeuesPostData = {
    body?: never;
    path: {
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query?: never;
    url: '/api/chunks/{chunk_id}/requeues';
};

export type RequeueChunkApiChunksChunkIdRequeuesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RequeueChunkApiChunksChunkIdRequeuesPostError = RequeueChunkApiChunksChunkIdRequeuesPostErrors[keyof RequeueChunkApiChunksChunkIdRequeuesPostErrors];

export type RequeueChunkApiChunksChunkIdRequeuesPostResponses = {
    /**
     * Successful Response
     */
    202: RequeueResponse;
};

export type RequeueChunkApiChunksChunkIdRequeuesPostResponse = RequeueChunkApiChunksChunkIdRequeuesPostResponses[keyof RequeueChunkApiChunksChunkIdRequeuesPostResponses];

export type OpenTakeoverApiChunksChunkIdTakeoversPostData = {
    body: TakeoverRequest;
    path: {
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query?: never;
    url: '/api/chunks/{chunk_id}/takeovers';
};

export type OpenTakeoverApiChunksChunkIdTakeoversPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OpenTakeoverApiChunksChunkIdTakeoversPostError = OpenTakeoverApiChunksChunkIdTakeoversPostErrors[keyof OpenTakeoverApiChunksChunkIdTakeoversPostErrors];

export type OpenTakeoverApiChunksChunkIdTakeoversPostResponses = {
    /**
     * Successful Response
     */
    201: TakeoverOpenResponse;
};

export type OpenTakeoverApiChunksChunkIdTakeoversPostResponse = OpenTakeoverApiChunksChunkIdTakeoversPostResponses[keyof OpenTakeoverApiChunksChunkIdTakeoversPostResponses];

export type EndTakeoverApiChunksChunkIdTakeoversTakeoverIdPatchData = {
    body?: never;
    path: {
        /**
         * Chunk Id
         */
        chunk_id: string;
        /**
         * Takeover Id
         */
        takeover_id: string;
    };
    query?: never;
    url: '/api/chunks/{chunk_id}/takeovers/{takeover_id}';
};

export type EndTakeoverApiChunksChunkIdTakeoversTakeoverIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EndTakeoverApiChunksChunkIdTakeoversTakeoverIdPatchError = EndTakeoverApiChunksChunkIdTakeoversTakeoverIdPatchErrors[keyof EndTakeoverApiChunksChunkIdTakeoversTakeoverIdPatchErrors];

export type EndTakeoverApiChunksChunkIdTakeoversTakeoverIdPatchResponses = {
    /**
     * Successful Response
     */
    200: TakeoverEndResponse;
};

export type EndTakeoverApiChunksChunkIdTakeoversTakeoverIdPatchResponse = EndTakeoverApiChunksChunkIdTakeoversTakeoverIdPatchResponses[keyof EndTakeoverApiChunksChunkIdTakeoversTakeoverIdPatchResponses];

export type ListEnvironmentsApiEnvironmentsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/environments';
};

export type ListEnvironmentsApiEnvironmentsGetResponses = {
    /**
     * Successful Response
     */
    200: EnvironmentListResponse;
};

export type ListEnvironmentsApiEnvironmentsGetResponse = ListEnvironmentsApiEnvironmentsGetResponses[keyof ListEnvironmentsApiEnvironmentsGetResponses];

export type ListEscalationsApiEscalationsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/escalations';
};

export type ListEscalationsApiEscalationsGetResponses = {
    /**
     * Successful Response
     */
    200: EscalationListResponse;
};

export type ListEscalationsApiEscalationsGetResponse = ListEscalationsApiEscalationsGetResponses[keyof ListEscalationsApiEscalationsGetResponses];

export type HealthApiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthApiHealthGetResponses = {
    /**
     * Response Health Api Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthApiHealthGetResponse = HealthApiHealthGetResponses[keyof HealthApiHealthGetResponses];

export type HeartbeatApiHeartbeatPostData = {
    body: HeartbeatRequest;
    path?: never;
    query?: never;
    url: '/api/heartbeat';
};

export type HeartbeatApiHeartbeatPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HeartbeatApiHeartbeatPostError = HeartbeatApiHeartbeatPostErrors[keyof HeartbeatApiHeartbeatPostErrors];

export type HeartbeatApiHeartbeatPostResponses = {
    /**
     * Successful Response
     */
    200: HeartbeatResponse;
};

export type HeartbeatApiHeartbeatPostResponse = HeartbeatApiHeartbeatPostResponses[keyof HeartbeatApiHeartbeatPostResponses];

export type ListLeasesApiLeasesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/leases';
};

export type ListLeasesApiLeasesGetResponses = {
    /**
     * Successful Response
     */
    200: LeaseListResponse;
};

export type ListLeasesApiLeasesGetResponse = ListLeasesApiLeasesGetResponses[keyof ListLeasesApiLeasesGetResponses];

export type RecordAskApiLeasesLeaseIdAsksPostData = {
    body: AskRequest;
    path: {
        /**
         * Lease Id
         */
        lease_id: string;
    };
    query?: never;
    url: '/api/leases/{lease_id}/asks';
};

export type RecordAskApiLeasesLeaseIdAsksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecordAskApiLeasesLeaseIdAsksPostError = RecordAskApiLeasesLeaseIdAsksPostErrors[keyof RecordAskApiLeasesLeaseIdAsksPostErrors];

export type RecordAskApiLeasesLeaseIdAsksPostResponses = {
    /**
     * Successful Response
     */
    201: AskResponse;
};

export type RecordAskApiLeasesLeaseIdAsksPostResponse = RecordAskApiLeasesLeaseIdAsksPostResponses[keyof RecordAskApiLeasesLeaseIdAsksPostResponses];

export type SessionEndApiLeasesLeaseIdSessionEndPostData = {
    body?: never;
    path: {
        /**
         * Lease Id
         */
        lease_id: string;
    };
    query?: never;
    url: '/api/leases/{lease_id}/session-end';
};

export type SessionEndApiLeasesLeaseIdSessionEndPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SessionEndApiLeasesLeaseIdSessionEndPostError = SessionEndApiLeasesLeaseIdSessionEndPostErrors[keyof SessionEndApiLeasesLeaseIdSessionEndPostErrors];

export type SessionEndApiLeasesLeaseIdSessionEndPostResponses = {
    /**
     * Successful Response
     */
    200: SessionEndResponse;
};

export type SessionEndApiLeasesLeaseIdSessionEndPostResponse = SessionEndApiLeasesLeaseIdSessionEndPostResponses[keyof SessionEndApiLeasesLeaseIdSessionEndPostResponses];

export type GetTranscriptApiLeasesLeaseIdTranscriptGetData = {
    body?: never;
    path: {
        /**
         * Lease Id
         */
        lease_id: string;
    };
    query?: never;
    url: '/api/leases/{lease_id}/transcript';
};

export type GetTranscriptApiLeasesLeaseIdTranscriptGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTranscriptApiLeasesLeaseIdTranscriptGetError = GetTranscriptApiLeasesLeaseIdTranscriptGetErrors[keyof GetTranscriptApiLeasesLeaseIdTranscriptGetErrors];

export type GetTranscriptApiLeasesLeaseIdTranscriptGetResponses = {
    /**
     * Successful Response
     */
    200: TranscriptResponse;
};

export type GetTranscriptApiLeasesLeaseIdTranscriptGetResponse = GetTranscriptApiLeasesLeaseIdTranscriptGetResponses[keyof GetTranscriptApiLeasesLeaseIdTranscriptGetResponses];

export type ReadyApiReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ready';
};

export type ReadyApiReadyGetResponses = {
    /**
     * Successful Response
     */
    200: ReadinessResponse;
};

export type ReadyApiReadyGetResponse = ReadyApiReadyGetResponses[keyof ReadyApiReadyGetResponses];

export type GetRunnerApiRunnerGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/runner';
};

export type GetRunnerApiRunnerGetResponses = {
    /**
     * Successful Response
     */
    200: RunnerStatusView;
};

export type GetRunnerApiRunnerGetResponse = GetRunnerApiRunnerGetResponses[keyof GetRunnerApiRunnerGetResponses];

export type PatchRunnerApiRunnerPatchData = {
    body: RunnerControlPatch;
    path?: never;
    query?: never;
    url: '/api/runner';
};

export type PatchRunnerApiRunnerPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchRunnerApiRunnerPatchError = PatchRunnerApiRunnerPatchErrors[keyof PatchRunnerApiRunnerPatchErrors];

export type PatchRunnerApiRunnerPatchResponses = {
    /**
     * Successful Response
     */
    200: RunnerControlView;
};

export type PatchRunnerApiRunnerPatchResponse = PatchRunnerApiRunnerPatchResponses[keyof PatchRunnerApiRunnerPatchResponses];

export type StartSelftestApiSelftestsPostData = {
    body: SelfTestStartRequest;
    path?: never;
    query?: never;
    url: '/api/selftests';
};

export type StartSelftestApiSelftestsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartSelftestApiSelftestsPostError = StartSelftestApiSelftestsPostErrors[keyof StartSelftestApiSelftestsPostErrors];

export type StartSelftestApiSelftestsPostResponses = {
    /**
     * Successful Response
     */
    201: SelfTestView;
};

export type StartSelftestApiSelftestsPostResponse = StartSelftestApiSelftestsPostResponses[keyof StartSelftestApiSelftestsPostResponses];

export type GetSelftestApiSelftestsSelftestIdGetData = {
    body?: never;
    path: {
        /**
         * Selftest Id
         */
        selftest_id: string;
    };
    query?: never;
    url: '/api/selftests/{selftest_id}';
};

export type GetSelftestApiSelftestsSelftestIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSelftestApiSelftestsSelftestIdGetError = GetSelftestApiSelftestsSelftestIdGetErrors[keyof GetSelftestApiSelftestsSelftestIdGetErrors];

export type GetSelftestApiSelftestsSelftestIdGetResponses = {
    /**
     * Successful Response
     */
    200: SelfTestView;
};

export type GetSelftestApiSelftestsSelftestIdGetResponse = GetSelftestApiSelftestsSelftestIdGetResponses[keyof GetSelftestApiSelftestsSelftestIdGetResponses];

export type ListOpenTakeoversApiTakeoversGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/takeovers';
};

export type ListOpenTakeoversApiTakeoversGetResponses = {
    /**
     * Successful Response
     */
    200: OpenTakeoverListResponse;
};

export type ListOpenTakeoversApiTakeoversGetResponse = ListOpenTakeoversApiTakeoversGetResponses[keyof ListOpenTakeoversApiTakeoversGetResponses];

export type ReadWorkspacePromptApiWorkspacePromptGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/workspace-prompt';
};

export type ReadWorkspacePromptApiWorkspacePromptGetResponses = {
    /**
     * Successful Response
     */
    200: WorkspacePromptResponse;
};

export type ReadWorkspacePromptApiWorkspacePromptGetResponse = ReadWorkspacePromptApiWorkspacePromptGetResponses[keyof ReadWorkspacePromptApiWorkspacePromptGetResponses];

export type ReplaceWorkspacePromptApiWorkspacePromptPutData = {
    body: WorkspacePromptReplacement;
    path?: never;
    query?: never;
    url: '/api/workspace-prompt';
};

export type ReplaceWorkspacePromptApiWorkspacePromptPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReplaceWorkspacePromptApiWorkspacePromptPutError = ReplaceWorkspacePromptApiWorkspacePromptPutErrors[keyof ReplaceWorkspacePromptApiWorkspacePromptPutErrors];

export type ReplaceWorkspacePromptApiWorkspacePromptPutResponses = {
    /**
     * Successful Response
     */
    200: WorkspacePromptResponse;
};

export type ReplaceWorkspacePromptApiWorkspacePromptPutResponse = ReplaceWorkspacePromptApiWorkspacePromptPutResponses[keyof ReplaceWorkspacePromptApiWorkspacePromptPutResponses];
