"""The runner-owned OpenCode plugin scaffold (execution spec, "Runner-owned plugin").

Written beside the permission/plugin document ``opencode_worker_config.py`` writes (D7); its
``plugins`` entry names this file through :func:`plugin_reference`. Both jobs are degrade-only
by construction: a plugin that never loads, or whose callback raises, must never change a
turn's verdict, usage, or exit code — process liveness remains the sole correctness signal."""

from __future__ import annotations

from pathlib import Path

from blizzard.runner.harness.worker_settings import HEARTBEAT_HOOK_COMMAND

# Matches the pinned compatibility corpus's `contracts/opencode/1.18.25/success.json` shape.
PLUGIN_DIRNAME = "plugins"
PLUGIN_FILENAME = "blizzard-heartbeat.ts"

# The exact identity forwarded to a tool subprocess through `shell.env` — never the daemon's full environment.
LEASE_ENV_VARS: tuple[str, ...] = ("BLIZZARD_LEASE_ID", "BLIZZARD_LEASE_TOKEN")
SESSION_ENV_VAR = "BLIZZARD_SESSION_ID"

_LEASE_ENV_VARS_JS = ", ".join(f'"{name}"' for name in LEASE_ENV_VARS)


def render_plugin_source() -> str:
    """The plugin module's JS/TS text — generated, not hand-maintained, like ``config.py``'s
    ``blizzard-runner.toml`` scaffold. Every callback wraps its body in ``try``/``catch``:
    OpenCode's plugin channel is classified ``degraded`` on the pinned version
    (``contracts/opencode/1.18.25/manifest.json``), so nothing may assume host isolation."""
    return f"""// Generated by blizzard.runner.harness.internal.opencode_plugin — do not edit by hand.
//
// The runner-owned OpenCode plugin (execution spec, "Runner-owned plugin"). Both jobs below
// are degrade-only by construction: a failure here must never fail the tool call it observed,
// and never changes the turn's own outcome — process liveness remains the sole correctness
// signal for turn completion.
import type {{ Plugin }} from "@opencode-ai/plugin";

const LEASE_ENV_VARS = [{_LEASE_ENV_VARS_JS}];
const SESSION_ENV_VAR = "{SESSION_ENV_VAR}";

const plugin: Plugin = async ({{ $ }}) => ({{
  // After every completed tool call, including a child session's, softly nudge the lease's
  // heartbeat — duplicate calls are harmless because the runner endpoint is idempotent.
  async "tool.execute.after"() {{
    try {{
      await $`{HEARTBEAT_HOOK_COMMAND}`.quiet().nothrow();
    }} catch {{
      // A missing binary or a thrown spawn error is silent by design: this hook is a bonus
      // channel, and the worker's own process liveness is the only correctness signal.
    }}
  }},

  // Forward exactly the lease identity and the authoritative session id to a tool
  // subprocess's environment — never the daemon's full environment.
  async "shell.env"(input, output) {{
    try {{
      for (const name of LEASE_ENV_VARS) {{
        const value = process.env[name];
        if (value) output.env[name] = value;
      }}
      const sessionId = input.sessionID ?? process.env[SESSION_ENV_VAR];
      if (sessionId) output.env[SESSION_ENV_VAR] = sessionId;
    }} catch {{
      // Same discipline as the heartbeat hook above: identity passthrough never fails the
      // tool subprocess it was meant to help.
    }}
  }},
}});

export default plugin;
"""


def write_plugin(path: Path) -> str:
    """Render and persist the plugin at ``path``, idempotently — ``blizzard runner init``
    scaffolds it exactly as it does the worker config, and a re-run overwrites it with the
    current generated content rather than leaving a stale one behind."""
    source = render_plugin_source()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(source, encoding="utf-8")
    return source


def plugin_reference(path: Path) -> str:
    """The ``file://`` form the runner-owned worker config's ``plugin`` array carries for a
    scaffolded plugin at ``path`` — the same shape the pinned compatibility corpus's own
    fixtures already use."""
    return f"file://{path}"


__all__ = [
    "LEASE_ENV_VARS",
    "PLUGIN_DIRNAME",
    "PLUGIN_FILENAME",
    "SESSION_ENV_VAR",
    "plugin_reference",
    "render_plugin_source",
    "write_plugin",
]
